/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: enk3K4vZ6pmH6kVCoZJXGn

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: enk3K4vZ6pmH6kVCoZJXGn/projectModule

const data = {
  base: `${"plasmic_tokens_enk3K4vZ6pmH6kVCoZJXGn"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
