/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: eP71shKy28es

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TextField from "../../TextField"; // plasmic-import: nhNi86WWHkJQ/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicEditProfile.module.css"; // plasmic-import: eP71shKy28es/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 0qv-KGqIe6NJ/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Edit Profile",

    openGraph: {
      title: "Edit Profile",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    },
    twitter: {
      card: "summary_large_image" as const,
      title: "Edit Profile",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    }
  };
}

export type PlasmicEditProfile__VariantMembers = {};
export type PlasmicEditProfile__VariantsArgs = {};
type VariantPropType = keyof PlasmicEditProfile__VariantsArgs;
export const PlasmicEditProfile__VariantProps = new Array<VariantPropType>();

export type PlasmicEditProfile__ArgsType = {};
type ArgPropType = keyof PlasmicEditProfile__ArgsType;
export const PlasmicEditProfile__ArgProps = new Array<ArgPropType>();

export type PlasmicEditProfile__OverridesType = {
  editProfilePage?: Flex__<"div">;
  flex?: Flex__<"div">;
  container?: Flex__<"div">;
  h1?: Flex__<"h1">;
  firstNameContainer?: Flex__<typeof TextField>;
  firstNameError?: Flex__<"div">;
  firstNameErrorContent?: Flex__<"div">;
  lastNameContainer?: Flex__<typeof TextField>;
  lastNameError?: Flex__<"div">;
  lastNameErrorContent?: Flex__<"div">;
  continueButton?: Flex__<"button">;
  backButton?: Flex__<"button">;
};

export interface DefaultEditProfileProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicEditProfile__RenderFunc(props: {
  variants: PlasmicEditProfile__VariantsArgs;
  args: PlasmicEditProfile__ArgsType;
  overrides: PlasmicEditProfile__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "firstNameContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "lastNameContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"editProfilePage"}
          data-plasmic-override={overrides.editProfilePage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.editProfilePage
          )}
        >
          <div
            data-plasmic-name={"flex"}
            data-plasmic-override={overrides.flex}
            className={classNames("all", sty.flex)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames("all", sty.container)}
            >
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  "all",
                  "h1",
                  "h1__6FNNC",
                  "__wab_text",
                  sty.h1
                )}
              >
                {"Edit Profile"}
              </h1>
              <TextField
                data-plasmic-name={"firstNameContainer"}
                data-plasmic-override={overrides.firstNameContainer}
                autoComplete={["given-name"]}
                autoFocus={true}
                className={classNames("__wab_instance", sty.firstNameContainer)}
                description={"ex. name@example.com"}
                disabled={false}
                inputMode={"text"}
                label={
                  <div
                    className={classNames(
                      "all",
                      "__wab_text",
                      sty.text___2YfMb
                    )}
                  >
                    {"First Name"}
                  </div>
                }
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "firstNameContainer",
                    "value"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                placeholder={"..."}
                showDescription={false}
                showLabel={true}
                start={
                  <svg
                    className={classNames("all", sty.svg___9Pxoa)}
                    role={"img"}
                  />
                }
                type={"text"}
                value={generateStateValueProp($state, [
                  "firstNameContainer",
                  "value"
                ])}
              />

              <div
                data-plasmic-name={"firstNameError"}
                data-plasmic-override={overrides.firstNameError}
                className={classNames("all", sty.firstNameError)}
              >
                <div
                  data-plasmic-name={"firstNameErrorContent"}
                  data-plasmic-override={overrides.firstNameErrorContent}
                  className={classNames(
                    "all",
                    "__wab_text",
                    sty.firstNameErrorContent
                  )}
                >
                  {"..."}
                </div>
              </div>
              <TextField
                data-plasmic-name={"lastNameContainer"}
                data-plasmic-override={overrides.lastNameContainer}
                autoComplete={["family-name"]}
                autoFocus={false}
                className={classNames("__wab_instance", sty.lastNameContainer)}
                description={"ex. name@example.com"}
                disabled={false}
                inputMode={"text"}
                label={
                  <div
                    className={classNames("all", "__wab_text", sty.text___0MLq)}
                  >
                    {"Last Name"}
                  </div>
                }
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "lastNameContainer",
                    "value"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                placeholder={"..."}
                showDescription={false}
                showLabel={true}
                start={
                  <svg
                    className={classNames("all", sty.svg__ksGqe)}
                    role={"img"}
                  />
                }
                type={"text"}
                value={generateStateValueProp($state, [
                  "lastNameContainer",
                  "value"
                ])}
              />

              <div
                data-plasmic-name={"lastNameError"}
                data-plasmic-override={overrides.lastNameError}
                className={classNames("all", sty.lastNameError)}
              >
                <div
                  data-plasmic-name={"lastNameErrorContent"}
                  data-plasmic-override={overrides.lastNameErrorContent}
                  className={classNames(
                    "all",
                    "__wab_text",
                    sty.lastNameErrorContent
                  )}
                >
                  {"..."}
                </div>
              </div>
              <button
                data-plasmic-name={"continueButton"}
                data-plasmic-override={overrides.continueButton}
                className={classNames(
                  "all",
                  "button",
                  "button__6FNNC",
                  sty.continueButton
                )}
                ref={ref => {
                  $refs["continueButton"] = ref;
                }}
              >
                <div
                  className={classNames("all", "__wab_text", sty.text__bk2IZ)}
                >
                  {"Continue"}
                </div>
              </button>
              <button
                data-plasmic-name={"backButton"}
                data-plasmic-override={overrides.backButton}
                className={classNames(
                  "all",
                  "button",
                  "button__6FNNC",
                  sty.backButton
                )}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToProfile"] = true
                    ? (() => {
                        const actionArgs = { destination: `/profile` };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToProfile"] != null &&
                    typeof $steps["goToProfile"] === "object" &&
                    typeof $steps["goToProfile"].then === "function"
                  ) {
                    $steps["goToProfile"] = await $steps["goToProfile"];
                  }
                }}
                ref={ref => {
                  $refs["backButton"] = ref;
                }}
              >
                <div
                  className={classNames("all", "__wab_text", sty.text__gpjo6)}
                >
                  {"Go Back"}
                </div>
              </button>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  editProfilePage: [
    "editProfilePage",
    "flex",
    "container",
    "h1",
    "firstNameContainer",
    "firstNameError",
    "firstNameErrorContent",
    "lastNameContainer",
    "lastNameError",
    "lastNameErrorContent",
    "continueButton",
    "backButton"
  ],
  flex: [
    "flex",
    "container",
    "h1",
    "firstNameContainer",
    "firstNameError",
    "firstNameErrorContent",
    "lastNameContainer",
    "lastNameError",
    "lastNameErrorContent",
    "continueButton",
    "backButton"
  ],
  container: [
    "container",
    "h1",
    "firstNameContainer",
    "firstNameError",
    "firstNameErrorContent",
    "lastNameContainer",
    "lastNameError",
    "lastNameErrorContent",
    "continueButton",
    "backButton"
  ],
  h1: ["h1"],
  firstNameContainer: ["firstNameContainer"],
  firstNameError: ["firstNameError", "firstNameErrorContent"],
  firstNameErrorContent: ["firstNameErrorContent"],
  lastNameContainer: ["lastNameContainer"],
  lastNameError: ["lastNameError", "lastNameErrorContent"],
  lastNameErrorContent: ["lastNameErrorContent"],
  continueButton: ["continueButton"],
  backButton: ["backButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  editProfilePage: "div";
  flex: "div";
  container: "div";
  h1: "h1";
  firstNameContainer: typeof TextField;
  firstNameError: "div";
  firstNameErrorContent: "div";
  lastNameContainer: typeof TextField;
  lastNameError: "div";
  lastNameErrorContent: "div";
  continueButton: "button";
  backButton: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicEditProfile__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicEditProfile__VariantsArgs;
    args?: PlasmicEditProfile__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicEditProfile__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicEditProfile__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicEditProfile__ArgProps,
          internalVariantPropNames: PlasmicEditProfile__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicEditProfile__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "editProfilePage") {
    func.displayName = "PlasmicEditProfile";
  } else {
    func.displayName = `PlasmicEditProfile.${nodeName}`;
  }
  return func;
}

export const PlasmicEditProfile = Object.assign(
  // Top-level PlasmicEditProfile renders the root element
  makeNodeComponent("editProfilePage"),
  {
    // Helper components rendering sub-elements
    flex: makeNodeComponent("flex"),
    container: makeNodeComponent("container"),
    h1: makeNodeComponent("h1"),
    firstNameContainer: makeNodeComponent("firstNameContainer"),
    firstNameError: makeNodeComponent("firstNameError"),
    firstNameErrorContent: makeNodeComponent("firstNameErrorContent"),
    lastNameContainer: makeNodeComponent("lastNameContainer"),
    lastNameError: makeNodeComponent("lastNameError"),
    lastNameErrorContent: makeNodeComponent("lastNameErrorContent"),
    continueButton: makeNodeComponent("continueButton"),
    backButton: makeNodeComponent("backButton"),

    // Metadata about props expected for PlasmicEditProfile
    internalVariantProps: PlasmicEditProfile__VariantProps,
    internalArgProps: PlasmicEditProfile__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/edit-profile",
      pagePath: "/edit-profile",
      params: {},
      query: {}
    })
  }
);

export default PlasmicEditProfile;
/* prettier-ignore-end */
