/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: WBKgavr6Ho0g

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicVStack.module.css"; // plasmic-import: WBKgavr6Ho0g/css

export type PlasmicVStack__VariantMembers = {
  listFunction: "event" | "leaderboard" | "wasteTypes";
};
export type PlasmicVStack__VariantsArgs = {
  listFunction?: SingleChoiceArg<"event" | "leaderboard" | "wasteTypes">;
};
type VariantPropType = keyof PlasmicVStack__VariantsArgs;
export const PlasmicVStack__VariantProps = new Array<VariantPropType>(
  "listFunction"
);

export type PlasmicVStack__ArgsType = {};
type ArgPropType = keyof PlasmicVStack__ArgsType;
export const PlasmicVStack__ArgProps = new Array<ArgPropType>();

export type PlasmicVStack__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultVStackProps {
  listFunction?: SingleChoiceArg<"event" | "leaderboard" | "wasteTypes">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicVStack__RenderFunc(props: {
  variants: PlasmicVStack__VariantsArgs;
  args: PlasmicVStack__ArgsType;
  overrides: PlasmicVStack__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "listFunction",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.listFunction
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootlistFunction_event]: hasVariant(
            $state,
            "listFunction",
            "event"
          ),
          [sty.rootlistFunction_leaderboard]: hasVariant(
            $state,
            "listFunction",
            "leaderboard"
          )
        }
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicVStack__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicVStack__VariantsArgs;
    args?: PlasmicVStack__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicVStack__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicVStack__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicVStack__ArgProps,
          internalVariantPropNames: PlasmicVStack__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicVStack__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicVStack";
  } else {
    func.displayName = `PlasmicVStack.${nodeName}`;
  }
  return func;
}

export const PlasmicVStack = Object.assign(
  // Top-level PlasmicVStack renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicVStack
    internalVariantProps: PlasmicVStack__VariantProps,
    internalArgProps: PlasmicVStack__ArgProps
  }
);

export default PlasmicVStack;
/* prettier-ignore-end */
