/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsshSk91OxVyPg } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ShSK91OXVyPg/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsshSk91OxVyPg
});
