/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: bsLCN1wPMRSw

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicMessage.module.css"; // plasmic-import: bsLCN1wPMRSw/css

import XCloseIcon from "./icons/PlasmicIcon__XClose"; // plasmic-import: R5NpJDhUjGD_/icon

export type PlasmicMessage__VariantMembers = {
  warning: "warning";
};
export type PlasmicMessage__VariantsArgs = {
  warning?: SingleBooleanChoiceArg<"warning">;
};
type VariantPropType = keyof PlasmicMessage__VariantsArgs;
export const PlasmicMessage__VariantProps = new Array<VariantPropType>(
  "warning"
);

export type PlasmicMessage__ArgsType = {
  slot?: React.ReactNode;
  children?: React.ReactNode;
  closeButton2?: React.ReactNode;
};
type ArgPropType = keyof PlasmicMessage__ArgsType;
export const PlasmicMessage__ArgProps = new Array<ArgPropType>(
  "slot",
  "children",
  "closeButton2"
);

export type PlasmicMessage__OverridesType = {
  message?: Flex__<"div">;
  closeButton?: Flex__<"button">;
};

export interface DefaultMessageProps {
  slot?: React.ReactNode;
  children?: React.ReactNode;
  closeButton2?: React.ReactNode;
  warning?: SingleBooleanChoiceArg<"warning">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMessage__RenderFunc(props: {
  variants: PlasmicMessage__VariantsArgs;
  args: PlasmicMessage__ArgsType;
  overrides: PlasmicMessage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "warning",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.warning
      },
      {
        path: "isVisible",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => true
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    (() => {
      try {
        return $state.isVisible;
      } catch (e) {
        if (
          e instanceof TypeError ||
          e?.plasmicType === "PlasmicUndefinedDataError"
        ) {
          return true;
        }
        throw e;
      }
    })() ? (
      <div
        data-plasmic-name={"message"}
        data-plasmic-override={overrides.message}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          "all",
          "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
          "plasmic_default_styles",
          "plasmic_mixins",
          styleTokensClassNames,
          sty.message,
          { [sty.messagewarning]: hasVariant($state, "warning", "warning") }
        )}
      >
        <div
          className={classNames("all", sty.freeBox__jn2Ex, {
            [sty.freeBoxwarning__jn2Ex87Qmq]: hasVariant(
              $state,
              "warning",
              "warning"
            )
          })}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <div className={classNames("all", "__wab_text", sty.text__wcGc)}>
                <React.Fragment>
                  <span
                    className={
                      "plasmic_default__all plasmic_default__span plasmic_default__span__6FNNC"
                    }
                    style={{ fontWeight: 700 }}
                  >
                    {"Warning!"}
                  </span>
                </React.Fragment>
              </div>
            ),
            value: args.slot,
            className: classNames(sty.slotTargetSlot, {
              [sty.slotTargetSlotwarning]: hasVariant(
                $state,
                "warning",
                "warning"
              )
            })
          })}
        </div>
        <div
          className={classNames("all", sty.freeBox__mh7Dl, {
            [sty.freeBoxwarning__mh7Dl87Qmq]: hasVariant(
              $state,
              "warning",
              "warning"
            )
          })}
        >
          {renderPlasmicSlot({
            defaultContents:
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            value: args.children,
            className: classNames(sty.slotTargetChildren, {
              [sty.slotTargetChildrenwarning]: hasVariant(
                $state,
                "warning",
                "warning"
              )
            })
          })}
          <button
            data-plasmic-name={"closeButton"}
            data-plasmic-override={overrides.closeButton}
            className={classNames(
              "all",
              "button",
              "button__6FNNC",
              sty.closeButton,
              {
                [sty.closeButtonwarning]: hasVariant(
                  $state,
                  "warning",
                  "warning"
                )
              }
            )}
            onClick={async event => {
              const $steps = {};

              $steps["updateIsVisible"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["isVisible"]
                      },
                      operation: 0,
                      value: false
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateIsVisible"] != null &&
                typeof $steps["updateIsVisible"] === "object" &&
                typeof $steps["updateIsVisible"].then === "function"
              ) {
                $steps["updateIsVisible"] = await $steps["updateIsVisible"];
              }
            }}
            ref={ref => {
              $refs["closeButton"] = ref;
            }}
          >
            {renderPlasmicSlot({
              defaultContents: (
                <XCloseIcon
                  className={classNames("all", sty.svg__c4Hw5)}
                  role={"img"}
                />
              ),

              value: args.closeButton2
            })}
          </button>
        </div>
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  message: ["message", "closeButton"],
  closeButton: ["closeButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  message: "div";
  closeButton: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMessage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMessage__VariantsArgs;
    args?: PlasmicMessage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicMessage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicMessage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMessage__ArgProps,
          internalVariantPropNames: PlasmicMessage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMessage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "message") {
    func.displayName = "PlasmicMessage";
  } else {
    func.displayName = `PlasmicMessage.${nodeName}`;
  }
  return func;
}

export const PlasmicMessage = Object.assign(
  // Top-level PlasmicMessage renders the root element
  makeNodeComponent("message"),
  {
    // Helper components rendering sub-elements
    closeButton: makeNodeComponent("closeButton"),

    // Metadata about props expected for PlasmicMessage
    internalVariantProps: PlasmicMessage__VariantProps,
    internalArgProps: PlasmicMessage__ArgProps
  }
);

export default PlasmicMessage;
/* prettier-ignore-end */
