/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: k4hp2P0Ip_cu

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TextField from "../../TextField"; // plasmic-import: nhNi86WWHkJQ/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicLogIn.module.css"; // plasmic-import: k4hp2P0Ip_cu/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 0qv-KGqIe6NJ/icon
import Login2Icon from "../library_tabler_3_2_icons/icons/PlasmicIcon__Login2"; // plasmic-import: csbhyrMqT37P/icon
import EnterIcon from "./icons/PlasmicIcon__Enter"; // plasmic-import: P5DSv3AH-d_Z/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Log In",

    openGraph: {
      title: "Log In",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    },
    twitter: {
      card: "summary_large_image" as const,
      title: "Log In",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    }
  };
}

export type PlasmicLogIn__VariantMembers = {};
export type PlasmicLogIn__VariantsArgs = {};
type VariantPropType = keyof PlasmicLogIn__VariantsArgs;
export const PlasmicLogIn__VariantProps = new Array<VariantPropType>();

export type PlasmicLogIn__ArgsType = {};
type ArgPropType = keyof PlasmicLogIn__ArgsType;
export const PlasmicLogIn__ArgProps = new Array<ArgPropType>();

export type PlasmicLogIn__OverridesType = {
  logInPage?: Flex__<"div">;
  flex?: Flex__<"div">;
  container?: Flex__<"div">;
  title?: Flex__<"h1">;
  emailContainer?: Flex__<typeof TextField>;
  passwordContainer?: Flex__<typeof TextField>;
  logInButton?: Flex__<"button">;
  error?: Flex__<"div">;
  errorContent?: Flex__<"div">;
  signUpRedirect?: Flex__<"div">;
  h1?: Flex__<"h1">;
  signUpRedirectButton?: Flex__<"button">;
  alreadyLoggedIn?: Flex__<"div">;
  notice?: Flex__<"h1">;
  toDashboardButton?: Flex__<"button">;
};

export interface DefaultLogInProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLogIn__RenderFunc(props: {
  variants: PlasmicLogIn__VariantsArgs;
  args: PlasmicLogIn__ArgsType;
  overrides: PlasmicLogIn__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "emailContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "passwordContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"logInPage"}
          data-plasmic-override={overrides.logInPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.logInPage
          )}
        >
          <div
            data-plasmic-name={"flex"}
            data-plasmic-override={overrides.flex}
            className={classNames("all", sty.flex)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames("all", sty.container)}
            >
              <h1
                data-plasmic-name={"title"}
                data-plasmic-override={overrides.title}
                className={classNames(
                  "all",
                  "h1",
                  "h1__6FNNC",
                  "__wab_text",
                  sty.title
                )}
              >
                {"Log In"}
              </h1>
              <TextField
                data-plasmic-name={"emailContainer"}
                data-plasmic-override={overrides.emailContainer}
                autoComplete={["email"]}
                autoFocus={true}
                className={classNames("__wab_instance", sty.emailContainer)}
                description={"ex. name@example.com"}
                disabled={false}
                inputMode={"email"}
                label={
                  <div
                    className={classNames("all", "__wab_text", sty.text__pr7H3)}
                  >
                    {"Email\n"}
                  </div>
                }
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "emailContainer",
                    "value"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                placeholder={"..."}
                showDescription={false}
                showLabel={true}
                type={"email"}
                value={generateStateValueProp($state, [
                  "emailContainer",
                  "value"
                ])}
              />

              <TextField
                data-plasmic-name={"passwordContainer"}
                data-plasmic-override={overrides.passwordContainer}
                autoComplete={["off"]}
                className={classNames("__wab_instance", sty.passwordContainer)}
                description={""}
                disabled={false}
                inputMode={"none"}
                label={
                  <div
                    className={classNames(
                      "all",
                      "__wab_text",
                      sty.text___0FBtx
                    )}
                  >
                    {"Password"}
                  </div>
                }
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "passwordContainer",
                    "value"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                placeholder={"..."}
                showDescription={false}
                showLabel={true}
                type={"password"}
                value={generateStateValueProp($state, [
                  "passwordContainer",
                  "value"
                ])}
              />

              <button
                data-plasmic-name={"logInButton"}
                data-plasmic-override={overrides.logInButton}
                className={classNames(
                  "all",
                  "button",
                  "button__6FNNC",
                  sty.logInButton
                )}
                ref={ref => {
                  $refs["logInButton"] = ref;
                }}
              >
                <Login2Icon
                  className={classNames("all", sty.svg__cfmzD)}
                  role={"img"}
                />

                <div
                  className={classNames("all", "__wab_text", sty.text__phJ4W)}
                >
                  {"Continue"}
                </div>
              </button>
              <div
                data-plasmic-name={"error"}
                data-plasmic-override={overrides.error}
                className={classNames("all", sty.error)}
              >
                <div
                  data-plasmic-name={"errorContent"}
                  data-plasmic-override={overrides.errorContent}
                  className={classNames("all", "__wab_text", sty.errorContent)}
                >
                  {"Password must be..."}
                </div>
              </div>
              <div
                data-plasmic-name={"signUpRedirect"}
                data-plasmic-override={overrides.signUpRedirect}
                className={classNames("all", sty.signUpRedirect)}
              >
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    "all",
                    "h1",
                    "h1__6FNNC",
                    "__wab_text",
                    sty.h1
                  )}
                >
                  {"Don't have an account?"}
                </h1>
                <button
                  data-plasmic-name={"signUpRedirectButton"}
                  data-plasmic-override={overrides.signUpRedirectButton}
                  className={classNames(
                    "all",
                    "button",
                    "button__6FNNC",
                    sty.signUpRedirectButton
                  )}
                  onClick={async event => {
                    const $steps = {};

                    $steps["goToSignUp"] = true
                      ? (() => {
                          const actionArgs = { destination: `/register` };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToSignUp"] != null &&
                      typeof $steps["goToSignUp"] === "object" &&
                      typeof $steps["goToSignUp"].then === "function"
                    ) {
                      $steps["goToSignUp"] = await $steps["goToSignUp"];
                    }
                  }}
                  ref={ref => {
                    $refs["signUpRedirectButton"] = ref;
                  }}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__awxdC)}
                  >
                    {"Sign up"}
                  </div>
                </button>
              </div>
            </div>
            <div
              data-plasmic-name={"alreadyLoggedIn"}
              data-plasmic-override={overrides.alreadyLoggedIn}
              className={classNames("all", sty.alreadyLoggedIn)}
            >
              <h1
                data-plasmic-name={"notice"}
                data-plasmic-override={overrides.notice}
                className={classNames(
                  "all",
                  "h1",
                  "h1__6FNNC",
                  "__wab_text",
                  sty.notice
                )}
              >
                {"You are already logged in."}
              </h1>
              <button
                data-plasmic-name={"toDashboardButton"}
                data-plasmic-override={overrides.toDashboardButton}
                className={classNames(
                  "all",
                  "button",
                  "button__6FNNC",
                  sty.toDashboardButton
                )}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToDashboard"] = true
                    ? (() => {
                        const actionArgs = { destination: `/dashboard` };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToDashboard"] != null &&
                    typeof $steps["goToDashboard"] === "object" &&
                    typeof $steps["goToDashboard"].then === "function"
                  ) {
                    $steps["goToDashboard"] = await $steps["goToDashboard"];
                  }
                }}
                ref={ref => {
                  $refs["toDashboardButton"] = ref;
                }}
              >
                <EnterIcon
                  className={classNames("all", sty.svg__gpraC)}
                  role={"img"}
                />

                <div
                  className={classNames("all", "__wab_text", sty.text___8QVJd)}
                >
                  {"Go To Dashboard"}
                </div>
              </button>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  logInPage: [
    "logInPage",
    "flex",
    "container",
    "title",
    "emailContainer",
    "passwordContainer",
    "logInButton",
    "error",
    "errorContent",
    "signUpRedirect",
    "h1",
    "signUpRedirectButton",
    "alreadyLoggedIn",
    "notice",
    "toDashboardButton"
  ],
  flex: [
    "flex",
    "container",
    "title",
    "emailContainer",
    "passwordContainer",
    "logInButton",
    "error",
    "errorContent",
    "signUpRedirect",
    "h1",
    "signUpRedirectButton",
    "alreadyLoggedIn",
    "notice",
    "toDashboardButton"
  ],
  container: [
    "container",
    "title",
    "emailContainer",
    "passwordContainer",
    "logInButton",
    "error",
    "errorContent",
    "signUpRedirect",
    "h1",
    "signUpRedirectButton"
  ],
  title: ["title"],
  emailContainer: ["emailContainer"],
  passwordContainer: ["passwordContainer"],
  logInButton: ["logInButton"],
  error: ["error", "errorContent"],
  errorContent: ["errorContent"],
  signUpRedirect: ["signUpRedirect", "h1", "signUpRedirectButton"],
  h1: ["h1"],
  signUpRedirectButton: ["signUpRedirectButton"],
  alreadyLoggedIn: ["alreadyLoggedIn", "notice", "toDashboardButton"],
  notice: ["notice"],
  toDashboardButton: ["toDashboardButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  logInPage: "div";
  flex: "div";
  container: "div";
  title: "h1";
  emailContainer: typeof TextField;
  passwordContainer: typeof TextField;
  logInButton: "button";
  error: "div";
  errorContent: "div";
  signUpRedirect: "div";
  h1: "h1";
  signUpRedirectButton: "button";
  alreadyLoggedIn: "div";
  notice: "h1";
  toDashboardButton: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogIn__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogIn__VariantsArgs;
    args?: PlasmicLogIn__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLogIn__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLogIn__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogIn__ArgProps,
          internalVariantPropNames: PlasmicLogIn__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogIn__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "logInPage") {
    func.displayName = "PlasmicLogIn";
  } else {
    func.displayName = `PlasmicLogIn.${nodeName}`;
  }
  return func;
}

export const PlasmicLogIn = Object.assign(
  // Top-level PlasmicLogIn renders the root element
  makeNodeComponent("logInPage"),
  {
    // Helper components rendering sub-elements
    flex: makeNodeComponent("flex"),
    container: makeNodeComponent("container"),
    title: makeNodeComponent("title"),
    emailContainer: makeNodeComponent("emailContainer"),
    passwordContainer: makeNodeComponent("passwordContainer"),
    logInButton: makeNodeComponent("logInButton"),
    error: makeNodeComponent("error"),
    errorContent: makeNodeComponent("errorContent"),
    signUpRedirect: makeNodeComponent("signUpRedirect"),
    h1: makeNodeComponent("h1"),
    signUpRedirectButton: makeNodeComponent("signUpRedirectButton"),
    alreadyLoggedIn: makeNodeComponent("alreadyLoggedIn"),
    notice: makeNodeComponent("notice"),
    toDashboardButton: makeNodeComponent("toDashboardButton"),

    // Metadata about props expected for PlasmicLogIn
    internalVariantProps: PlasmicLogIn__VariantProps,
    internalArgProps: PlasmicLogIn__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/log-in",
      pagePath: "/log-in",
      params: {},
      query: {}
    })
  }
);

export default PlasmicLogIn;
/* prettier-ignore-end */
