/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: NdhG8kvmuxmI

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicLeaderboardListItem.module.css"; // plasmic-import: NdhG8kvmuxmI/css

import ProfileIcon from "./icons/PlasmicIcon__Profile"; // plasmic-import: OkMjqJNO-au2/icon
import StarFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__StarFilled"; // plasmic-import: hkZTt7XysTNC/icon

export type PlasmicLeaderboardListItem__VariantMembers = {};
export type PlasmicLeaderboardListItem__VariantsArgs = {};
type VariantPropType = keyof PlasmicLeaderboardListItem__VariantsArgs;
export const PlasmicLeaderboardListItem__VariantProps =
  new Array<VariantPropType>();

export type PlasmicLeaderboardListItem__ArgsType = {
  points?: number;
  displayName?: string;
  positionText?: string;
  joinDateText?: string;
};
type ArgPropType = keyof PlasmicLeaderboardListItem__ArgsType;
export const PlasmicLeaderboardListItem__ArgProps = new Array<ArgPropType>(
  "points",
  "displayName",
  "positionText",
  "joinDateText"
);

export type PlasmicLeaderboardListItem__OverridesType = {
  leaderboardListItem?: Flex__<"div">;
  leaderboardListItemHeader?: Flex__<"div">;
  leaderboardListItemPositionLabel?: Flex__<"h1">;
  leaderboardListItemProfileLayout?: Flex__<"div">;
  leaderboardListItemProfileInfoContainer?: Flex__<"div">;
  leaderboardListItemProfileUserNameLabel?: Flex__<"h1">;
  leaderboardListItemProfileJoinDateLabel?: Flex__<"div">;
  leaderboardListItemPointsStatContainer?: Flex__<"div">;
  leaderboardListItemPointsStatValueLabel?: Flex__<"h1">;
  leaderboardListItemPointsStatLabel?: Flex__<"h1">;
};

export interface DefaultLeaderboardListItemProps {
  points?: number;
  displayName?: string;
  positionText?: string;
  joinDateText?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLeaderboardListItem__RenderFunc(props: {
  variants: PlasmicLeaderboardListItem__VariantsArgs;
  args: PlasmicLeaderboardListItem__ArgsType;
  overrides: PlasmicLeaderboardListItem__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          points: 0,
          displayName: "User Name",
          positionText: "#1",
          joinDateText: "Joined YYYY-MM-DD"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"leaderboardListItem"}
      data-plasmic-override={overrides.leaderboardListItem}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.leaderboardListItem
      )}
    >
      <div
        data-plasmic-name={"leaderboardListItemHeader"}
        data-plasmic-override={overrides.leaderboardListItemHeader}
        className={classNames("all", sty.leaderboardListItemHeader)}
      >
        <h1
          data-plasmic-name={"leaderboardListItemPositionLabel"}
          data-plasmic-override={overrides.leaderboardListItemPositionLabel}
          className={classNames(
            "all",
            "h1",
            "h1__6FNNC",
            "__wab_text",
            sty.leaderboardListItemPositionLabel
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.positionText;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "#1";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </h1>
        <ProfileIcon
          className={classNames("all", sty.svg__hvYz)}
          role={"img"}
        />

        <div
          data-plasmic-name={"leaderboardListItemProfileLayout"}
          data-plasmic-override={overrides.leaderboardListItemProfileLayout}
          className={classNames("all", sty.leaderboardListItemProfileLayout)}
        >
          <div
            data-plasmic-name={"leaderboardListItemProfileInfoContainer"}
            data-plasmic-override={
              overrides.leaderboardListItemProfileInfoContainer
            }
            className={classNames(
              "all",
              sty.leaderboardListItemProfileInfoContainer
            )}
          >
            <h1
              data-plasmic-name={"leaderboardListItemProfileUserNameLabel"}
              data-plasmic-override={
                overrides.leaderboardListItemProfileUserNameLabel
              }
              className={classNames(
                "all",
                "h1",
                "h1__6FNNC",
                "__wab_text",
                sty.leaderboardListItemProfileUserNameLabel
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $props.displayName;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "User Name";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </h1>
            <div
              data-plasmic-name={"leaderboardListItemProfileJoinDateLabel"}
              data-plasmic-override={
                overrides.leaderboardListItemProfileJoinDateLabel
              }
              className={classNames(
                "all",
                "__wab_text",
                sty.leaderboardListItemProfileJoinDateLabel
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $props.joinDateText;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "Joined XXXX-XX-XX\n\r";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </div>
          <div
            data-plasmic-name={"leaderboardListItemPointsStatContainer"}
            data-plasmic-override={
              overrides.leaderboardListItemPointsStatContainer
            }
            className={classNames(
              "all",
              sty.leaderboardListItemPointsStatContainer
            )}
          >
            <StarFilledIcon
              className={classNames("all", sty.svg___2IlAr)}
              role={"img"}
            />

            <h1
              data-plasmic-name={"leaderboardListItemPointsStatValueLabel"}
              data-plasmic-override={
                overrides.leaderboardListItemPointsStatValueLabel
              }
              className={classNames(
                "all",
                "h1",
                "h1__6FNNC",
                "__wab_text",
                sty.leaderboardListItemPointsStatValueLabel
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $props.points;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "0";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </h1>
            <h1
              data-plasmic-name={"leaderboardListItemPointsStatLabel"}
              data-plasmic-override={
                overrides.leaderboardListItemPointsStatLabel
              }
              className={classNames(
                "all",
                "h1",
                "h1__6FNNC",
                "__wab_text",
                sty.leaderboardListItemPointsStatLabel
              )}
            >
              {"points"}
            </h1>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  leaderboardListItem: [
    "leaderboardListItem",
    "leaderboardListItemHeader",
    "leaderboardListItemPositionLabel",
    "leaderboardListItemProfileLayout",
    "leaderboardListItemProfileInfoContainer",
    "leaderboardListItemProfileUserNameLabel",
    "leaderboardListItemProfileJoinDateLabel",
    "leaderboardListItemPointsStatContainer",
    "leaderboardListItemPointsStatValueLabel",
    "leaderboardListItemPointsStatLabel"
  ],
  leaderboardListItemHeader: [
    "leaderboardListItemHeader",
    "leaderboardListItemPositionLabel",
    "leaderboardListItemProfileLayout",
    "leaderboardListItemProfileInfoContainer",
    "leaderboardListItemProfileUserNameLabel",
    "leaderboardListItemProfileJoinDateLabel",
    "leaderboardListItemPointsStatContainer",
    "leaderboardListItemPointsStatValueLabel",
    "leaderboardListItemPointsStatLabel"
  ],
  leaderboardListItemPositionLabel: ["leaderboardListItemPositionLabel"],
  leaderboardListItemProfileLayout: [
    "leaderboardListItemProfileLayout",
    "leaderboardListItemProfileInfoContainer",
    "leaderboardListItemProfileUserNameLabel",
    "leaderboardListItemProfileJoinDateLabel",
    "leaderboardListItemPointsStatContainer",
    "leaderboardListItemPointsStatValueLabel",
    "leaderboardListItemPointsStatLabel"
  ],
  leaderboardListItemProfileInfoContainer: [
    "leaderboardListItemProfileInfoContainer",
    "leaderboardListItemProfileUserNameLabel",
    "leaderboardListItemProfileJoinDateLabel"
  ],
  leaderboardListItemProfileUserNameLabel: [
    "leaderboardListItemProfileUserNameLabel"
  ],
  leaderboardListItemProfileJoinDateLabel: [
    "leaderboardListItemProfileJoinDateLabel"
  ],
  leaderboardListItemPointsStatContainer: [
    "leaderboardListItemPointsStatContainer",
    "leaderboardListItemPointsStatValueLabel",
    "leaderboardListItemPointsStatLabel"
  ],
  leaderboardListItemPointsStatValueLabel: [
    "leaderboardListItemPointsStatValueLabel"
  ],
  leaderboardListItemPointsStatLabel: ["leaderboardListItemPointsStatLabel"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  leaderboardListItem: "div";
  leaderboardListItemHeader: "div";
  leaderboardListItemPositionLabel: "h1";
  leaderboardListItemProfileLayout: "div";
  leaderboardListItemProfileInfoContainer: "div";
  leaderboardListItemProfileUserNameLabel: "h1";
  leaderboardListItemProfileJoinDateLabel: "div";
  leaderboardListItemPointsStatContainer: "div";
  leaderboardListItemPointsStatValueLabel: "h1";
  leaderboardListItemPointsStatLabel: "h1";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLeaderboardListItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLeaderboardListItem__VariantsArgs;
    args?: PlasmicLeaderboardListItem__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLeaderboardListItem__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLeaderboardListItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLeaderboardListItem__ArgProps,
          internalVariantPropNames: PlasmicLeaderboardListItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLeaderboardListItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "leaderboardListItem") {
    func.displayName = "PlasmicLeaderboardListItem";
  } else {
    func.displayName = `PlasmicLeaderboardListItem.${nodeName}`;
  }
  return func;
}

export const PlasmicLeaderboardListItem = Object.assign(
  // Top-level PlasmicLeaderboardListItem renders the root element
  makeNodeComponent("leaderboardListItem"),
  {
    // Helper components rendering sub-elements
    leaderboardListItemHeader: makeNodeComponent("leaderboardListItemHeader"),
    leaderboardListItemPositionLabel: makeNodeComponent(
      "leaderboardListItemPositionLabel"
    ),
    leaderboardListItemProfileLayout: makeNodeComponent(
      "leaderboardListItemProfileLayout"
    ),
    leaderboardListItemProfileInfoContainer: makeNodeComponent(
      "leaderboardListItemProfileInfoContainer"
    ),
    leaderboardListItemProfileUserNameLabel: makeNodeComponent(
      "leaderboardListItemProfileUserNameLabel"
    ),
    leaderboardListItemProfileJoinDateLabel: makeNodeComponent(
      "leaderboardListItemProfileJoinDateLabel"
    ),
    leaderboardListItemPointsStatContainer: makeNodeComponent(
      "leaderboardListItemPointsStatContainer"
    ),
    leaderboardListItemPointsStatValueLabel: makeNodeComponent(
      "leaderboardListItemPointsStatValueLabel"
    ),
    leaderboardListItemPointsStatLabel: makeNodeComponent(
      "leaderboardListItemPointsStatLabel"
    ),

    // Metadata about props expected for PlasmicLeaderboardListItem
    internalVariantProps: PlasmicLeaderboardListItem__VariantProps,
    internalArgProps: PlasmicLeaderboardListItem__ArgProps
  }
);

export default PlasmicLeaderboardListItem;
/* prettier-ignore-end */
