/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: lLmZHWk7BVTv

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Select from "../../Select"; // plasmic-import: LVXNSsX6u6_R/component
import MenuItem from "../../MenuItem"; // plasmic-import: -PDYsBUwNZcp/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicLogWaste.module.css"; // plasmic-import: lLmZHWk7BVTv/css

import SquareCheckIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__SquareCheck"; // plasmic-import: 6SDNahuMIAdO/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Log Waste",

    openGraph: {
      title: "Log Waste",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    },
    twitter: {
      card: "summary_large_image" as const,
      title: "Log Waste",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    }
  };
}

export type PlasmicLogWaste__VariantMembers = {};
export type PlasmicLogWaste__VariantsArgs = {};
type VariantPropType = keyof PlasmicLogWaste__VariantsArgs;
export const PlasmicLogWaste__VariantProps = new Array<VariantPropType>();

export type PlasmicLogWaste__ArgsType = {};
type ArgPropType = keyof PlasmicLogWaste__ArgsType;
export const PlasmicLogWaste__ArgProps = new Array<ArgPropType>();

export type PlasmicLogWaste__OverridesType = {
  logWastePage?: Flex__<"div">;
  flex?: Flex__<"div">;
  error?: Flex__<"div">;
  errorContent?: Flex__<"div">;
  container?: Flex__<"div">;
  title?: Flex__<"h1">;
  wasteTypeContainer?: Flex__<"div">;
  wasteTypeColor?: Flex__<"div">;
  wasteTypeSelector?: Flex__<typeof Select>;
  menuItem?: Flex__<typeof MenuItem>;
  cameraFeedContainer?: Flex__<"div">;
  submitButton?: Flex__<"button">;
  backButton?: Flex__<"button">;
};

export interface DefaultLogWasteProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLogWaste__RenderFunc(props: {
  variants: PlasmicLogWaste__VariantsArgs;
  args: PlasmicLogWaste__ArgsType;
  overrides: PlasmicLogWaste__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "wasteTypeSelector.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "wasteTypeSelector.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"logWastePage"}
          data-plasmic-override={overrides.logWastePage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.logWastePage
          )}
        >
          <div
            data-plasmic-name={"flex"}
            data-plasmic-override={overrides.flex}
            className={classNames("all", sty.flex)}
          >
            <div
              data-plasmic-name={"error"}
              data-plasmic-override={overrides.error}
              className={classNames("all", sty.error)}
            >
              <div
                data-plasmic-name={"errorContent"}
                data-plasmic-override={overrides.errorContent}
                className={classNames("all", "__wab_text", sty.errorContent)}
              >
                {"Error"}
              </div>
            </div>
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames("all", sty.container)}
            >
              <h1
                data-plasmic-name={"title"}
                data-plasmic-override={overrides.title}
                className={classNames(
                  "all",
                  "h1",
                  "h1__6FNNC",
                  "__wab_text",
                  sty.title
                )}
              >
                {"Log Waste"}
              </h1>
              <div
                data-plasmic-name={"wasteTypeContainer"}
                data-plasmic-override={overrides.wasteTypeContainer}
                className={classNames("all", sty.wasteTypeContainer)}
              >
                <div
                  data-plasmic-name={"wasteTypeColor"}
                  data-plasmic-override={overrides.wasteTypeColor}
                  className={classNames("all", sty.wasteTypeColor)}
                />

                <Select
                  data-plasmic-name={"wasteTypeSelector"}
                  data-plasmic-override={overrides.wasteTypeSelector}
                  className={classNames(
                    "__wab_instance",
                    sty.wasteTypeSelector
                  )}
                  isOpen={generateStateValueProp($state, [
                    "wasteTypeSelector",
                    "isOpen"
                  ])}
                  items={
                    <MenuItem
                      data-plasmic-name={"menuItem"}
                      data-plasmic-override={overrides.menuItem}
                      label={"Waste Type"}
                      value={""}
                    />
                  }
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "wasteTypeSelector",
                      "value"
                    ]).apply(null, eventArgs);

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                  onOpenChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "wasteTypeSelector",
                      "isOpen"
                    ]).apply(null, eventArgs);

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                  placeholder={"Waste type..."}
                  showDescription={false}
                  showLabel={false}
                  value={generateStateValueProp($state, [
                    "wasteTypeSelector",
                    "value"
                  ])}
                />
              </div>
              <div
                data-plasmic-name={"cameraFeedContainer"}
                data-plasmic-override={overrides.cameraFeedContainer}
                className={classNames("all", sty.cameraFeedContainer)}
              />

              <button
                data-plasmic-name={"submitButton"}
                data-plasmic-override={overrides.submitButton}
                className={classNames(
                  "all",
                  "button",
                  "button__6FNNC",
                  sty.submitButton
                )}
                ref={ref => {
                  $refs["submitButton"] = ref;
                }}
              >
                <SquareCheckIcon
                  className={classNames("all", sty.svg__oqsq2)}
                  role={"img"}
                />

                <div
                  className={classNames("all", "__wab_text", sty.text___0ElJk)}
                >
                  {"Submit"}
                </div>
              </button>
              <button
                data-plasmic-name={"backButton"}
                data-plasmic-override={overrides.backButton}
                className={classNames(
                  "all",
                  "button",
                  "button__6FNNC",
                  sty.backButton
                )}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToDashboard"] = true
                    ? (() => {
                        const actionArgs = { destination: `/dashboard` };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToDashboard"] != null &&
                    typeof $steps["goToDashboard"] === "object" &&
                    typeof $steps["goToDashboard"].then === "function"
                  ) {
                    $steps["goToDashboard"] = await $steps["goToDashboard"];
                  }
                }}
                ref={ref => {
                  $refs["backButton"] = ref;
                }}
              >
                <SquareCheckIcon
                  className={classNames("all", sty.svg__k6Owj)}
                  role={"img"}
                />

                <div
                  className={classNames("all", "__wab_text", sty.text__fTzQd)}
                >
                  {"Go Back"}
                </div>
              </button>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  logWastePage: [
    "logWastePage",
    "flex",
    "error",
    "errorContent",
    "container",
    "title",
    "wasteTypeContainer",
    "wasteTypeColor",
    "wasteTypeSelector",
    "menuItem",
    "cameraFeedContainer",
    "submitButton",
    "backButton"
  ],
  flex: [
    "flex",
    "error",
    "errorContent",
    "container",
    "title",
    "wasteTypeContainer",
    "wasteTypeColor",
    "wasteTypeSelector",
    "menuItem",
    "cameraFeedContainer",
    "submitButton",
    "backButton"
  ],
  error: ["error", "errorContent"],
  errorContent: ["errorContent"],
  container: [
    "container",
    "title",
    "wasteTypeContainer",
    "wasteTypeColor",
    "wasteTypeSelector",
    "menuItem",
    "cameraFeedContainer",
    "submitButton",
    "backButton"
  ],
  title: ["title"],
  wasteTypeContainer: [
    "wasteTypeContainer",
    "wasteTypeColor",
    "wasteTypeSelector",
    "menuItem"
  ],
  wasteTypeColor: ["wasteTypeColor"],
  wasteTypeSelector: ["wasteTypeSelector", "menuItem"],
  menuItem: ["menuItem"],
  cameraFeedContainer: ["cameraFeedContainer"],
  submitButton: ["submitButton"],
  backButton: ["backButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  logWastePage: "div";
  flex: "div";
  error: "div";
  errorContent: "div";
  container: "div";
  title: "h1";
  wasteTypeContainer: "div";
  wasteTypeColor: "div";
  wasteTypeSelector: typeof Select;
  menuItem: typeof MenuItem;
  cameraFeedContainer: "div";
  submitButton: "button";
  backButton: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogWaste__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogWaste__VariantsArgs;
    args?: PlasmicLogWaste__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLogWaste__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLogWaste__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogWaste__ArgProps,
          internalVariantPropNames: PlasmicLogWaste__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogWaste__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "logWastePage") {
    func.displayName = "PlasmicLogWaste";
  } else {
    func.displayName = `PlasmicLogWaste.${nodeName}`;
  }
  return func;
}

export const PlasmicLogWaste = Object.assign(
  // Top-level PlasmicLogWaste renders the root element
  makeNodeComponent("logWastePage"),
  {
    // Helper components rendering sub-elements
    flex: makeNodeComponent("flex"),
    error: makeNodeComponent("error"),
    errorContent: makeNodeComponent("errorContent"),
    container: makeNodeComponent("container"),
    title: makeNodeComponent("title"),
    wasteTypeContainer: makeNodeComponent("wasteTypeContainer"),
    wasteTypeColor: makeNodeComponent("wasteTypeColor"),
    wasteTypeSelector: makeNodeComponent("wasteTypeSelector"),
    menuItem: makeNodeComponent("menuItem"),
    cameraFeedContainer: makeNodeComponent("cameraFeedContainer"),
    submitButton: makeNodeComponent("submitButton"),
    backButton: makeNodeComponent("backButton"),

    // Metadata about props expected for PlasmicLogWaste
    internalVariantProps: PlasmicLogWaste__VariantProps,
    internalArgProps: PlasmicLogWaste__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/log-waste",
      pagePath: "/log-waste",
      params: {},
      query: {}
    })
  }
);

export default PlasmicLogWaste;
/* prettier-ignore-end */
