/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: 2Ie9kOJo2875

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TextField from "../../TextField"; // plasmic-import: nhNi86WWHkJQ/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicChangeEmail.module.css"; // plasmic-import: 2Ie9kOJo2875/css

import MailIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__Mail"; // plasmic-import: g0KBv68uO4-w/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 0qv-KGqIe6NJ/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Change Email",

    openGraph: {
      title: "Change Email",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    },
    twitter: {
      card: "summary_large_image" as const,
      title: "Change Email",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    }
  };
}

export type PlasmicChangeEmail__VariantMembers = {};
export type PlasmicChangeEmail__VariantsArgs = {};
type VariantPropType = keyof PlasmicChangeEmail__VariantsArgs;
export const PlasmicChangeEmail__VariantProps = new Array<VariantPropType>();

export type PlasmicChangeEmail__ArgsType = {};
type ArgPropType = keyof PlasmicChangeEmail__ArgsType;
export const PlasmicChangeEmail__ArgProps = new Array<ArgPropType>();

export type PlasmicChangeEmail__OverridesType = {
  changePasswordPage?: Flex__<"div">;
  flex?: Flex__<"div">;
  container?: Flex__<"div">;
  h1?: Flex__<"h1">;
  error?: Flex__<"div">;
  passwordErrorContent?: Flex__<"div">;
  newEmailContainer?: Flex__<typeof TextField>;
  svg?: Flex__<"svg">;
  continueButton?: Flex__<"button">;
  successContainer?: Flex__<"div">;
  notice?: Flex__<"h1">;
  toDashboardButton?: Flex__<"button">;
};

export interface DefaultChangeEmailProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicChangeEmail__RenderFunc(props: {
  variants: PlasmicChangeEmail__VariantsArgs;
  args: PlasmicChangeEmail__ArgsType;
  overrides: PlasmicChangeEmail__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "newEmailContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"changePasswordPage"}
          data-plasmic-override={overrides.changePasswordPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.changePasswordPage
          )}
        >
          <div
            data-plasmic-name={"flex"}
            data-plasmic-override={overrides.flex}
            className={classNames("all", sty.flex)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames("all", sty.container)}
            >
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  "all",
                  "h1",
                  "h1__6FNNC",
                  "__wab_text",
                  sty.h1
                )}
              >
                {"Change Email"}
              </h1>
              <div
                data-plasmic-name={"error"}
                data-plasmic-override={overrides.error}
                className={classNames("all", sty.error)}
              >
                <div
                  data-plasmic-name={"passwordErrorContent"}
                  data-plasmic-override={overrides.passwordErrorContent}
                  className={classNames(
                    "all",
                    "__wab_text",
                    sty.passwordErrorContent
                  )}
                >
                  {"Password must be..."}
                </div>
              </div>
              <TextField
                data-plasmic-name={"newEmailContainer"}
                data-plasmic-override={overrides.newEmailContainer}
                autoComplete={["email"]}
                autoFocus={true}
                className={classNames("__wab_instance", sty.newEmailContainer)}
                description={"ex. name@example.com"}
                disabled={false}
                iconStart={true}
                inputMode={"email"}
                label={
                  <div
                    className={classNames("all", "__wab_text", sty.text__vv1QZ)}
                  >
                    {"New Email Address\n"}
                  </div>
                }
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "newEmailContainer",
                    "value"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                placeholder={"..."}
                showDescription={false}
                showLabel={true}
                start={
                  <MailIcon
                    data-plasmic-name={"svg"}
                    data-plasmic-override={overrides.svg}
                    className={classNames("all", sty.svg)}
                    role={"img"}
                  />
                }
                type={"email"}
                value={generateStateValueProp($state, [
                  "newEmailContainer",
                  "value"
                ])}
              />

              <button
                data-plasmic-name={"continueButton"}
                data-plasmic-override={overrides.continueButton}
                className={classNames(
                  "all",
                  "button",
                  "button__6FNNC",
                  sty.continueButton
                )}
                ref={ref => {
                  $refs["continueButton"] = ref;
                }}
              >
                <div
                  className={classNames("all", "__wab_text", sty.text__f1Oxw)}
                >
                  {"Continue"}
                </div>
              </button>
            </div>
            <div
              data-plasmic-name={"successContainer"}
              data-plasmic-override={overrides.successContainer}
              className={classNames("all", sty.successContainer)}
            >
              <h1
                data-plasmic-name={"notice"}
                data-plasmic-override={overrides.notice}
                className={classNames(
                  "all",
                  "h1",
                  "h1__6FNNC",
                  "__wab_text",
                  sty.notice
                )}
              >
                <React.Fragment>
                  <span
                    className={
                      "plasmic_default__all plasmic_default__span plasmic_default__span__6FNNC"
                    }
                    style={{ color: "var(--token-ytzaa9i3sK9d)" }}
                  >
                    {"Success!"}
                  </span>
                  <React.Fragment>
                    {"\n\nYour email address has  been updated."}
                  </React.Fragment>
                </React.Fragment>
              </h1>
              <button
                data-plasmic-name={"toDashboardButton"}
                data-plasmic-override={overrides.toDashboardButton}
                className={classNames(
                  "all",
                  "button",
                  "button__6FNNC",
                  sty.toDashboardButton
                )}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToDashboard"] = true
                    ? (() => {
                        const actionArgs = { destination: `/dashboard` };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToDashboard"] != null &&
                    typeof $steps["goToDashboard"] === "object" &&
                    typeof $steps["goToDashboard"].then === "function"
                  ) {
                    $steps["goToDashboard"] = await $steps["goToDashboard"];
                  }
                }}
                ref={ref => {
                  $refs["toDashboardButton"] = ref;
                }}
              >
                <div
                  className={classNames("all", "__wab_text", sty.text__i3FG)}
                >
                  {"Go To Dashboard"}
                </div>
              </button>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  changePasswordPage: [
    "changePasswordPage",
    "flex",
    "container",
    "h1",
    "error",
    "passwordErrorContent",
    "newEmailContainer",
    "svg",
    "continueButton",
    "successContainer",
    "notice",
    "toDashboardButton"
  ],
  flex: [
    "flex",
    "container",
    "h1",
    "error",
    "passwordErrorContent",
    "newEmailContainer",
    "svg",
    "continueButton",
    "successContainer",
    "notice",
    "toDashboardButton"
  ],
  container: [
    "container",
    "h1",
    "error",
    "passwordErrorContent",
    "newEmailContainer",
    "svg",
    "continueButton"
  ],
  h1: ["h1"],
  error: ["error", "passwordErrorContent"],
  passwordErrorContent: ["passwordErrorContent"],
  newEmailContainer: ["newEmailContainer", "svg"],
  svg: ["svg"],
  continueButton: ["continueButton"],
  successContainer: ["successContainer", "notice", "toDashboardButton"],
  notice: ["notice"],
  toDashboardButton: ["toDashboardButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  changePasswordPage: "div";
  flex: "div";
  container: "div";
  h1: "h1";
  error: "div";
  passwordErrorContent: "div";
  newEmailContainer: typeof TextField;
  svg: "svg";
  continueButton: "button";
  successContainer: "div";
  notice: "h1";
  toDashboardButton: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicChangeEmail__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicChangeEmail__VariantsArgs;
    args?: PlasmicChangeEmail__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicChangeEmail__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicChangeEmail__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicChangeEmail__ArgProps,
          internalVariantPropNames: PlasmicChangeEmail__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicChangeEmail__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "changePasswordPage") {
    func.displayName = "PlasmicChangeEmail";
  } else {
    func.displayName = `PlasmicChangeEmail.${nodeName}`;
  }
  return func;
}

export const PlasmicChangeEmail = Object.assign(
  // Top-level PlasmicChangeEmail renders the root element
  makeNodeComponent("changePasswordPage"),
  {
    // Helper components rendering sub-elements
    flex: makeNodeComponent("flex"),
    container: makeNodeComponent("container"),
    h1: makeNodeComponent("h1"),
    error: makeNodeComponent("error"),
    passwordErrorContent: makeNodeComponent("passwordErrorContent"),
    newEmailContainer: makeNodeComponent("newEmailContainer"),
    svg: makeNodeComponent("svg"),
    continueButton: makeNodeComponent("continueButton"),
    successContainer: makeNodeComponent("successContainer"),
    notice: makeNodeComponent("notice"),
    toDashboardButton: makeNodeComponent("toDashboardButton"),

    // Metadata about props expected for PlasmicChangeEmail
    internalVariantProps: PlasmicChangeEmail__VariantProps,
    internalArgProps: PlasmicChangeEmail__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/change-email",
      pagePath: "/change-email",
      params: {},
      query: {}
    })
  }
);

export default PlasmicChangeEmail;
/* prettier-ignore-end */
