/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: QSNcDEs3p2EG

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { InteractiveMap } from "../../InteractiveMap"; // plasmic-import: XvO_ZZU8bF0U/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicEventListItem.module.css"; // plasmic-import: QSNcDEs3p2EG/css

import CalendarIcon from "./icons/PlasmicIcon__Calendar"; // plasmic-import: CPTBTnszI8ug/icon
import PeopleIcon from "./icons/PlasmicIcon__People"; // plasmic-import: 9nm8GnVbav_y/icon
import MovingTrashIcon from "./icons/PlasmicIcon__MovingTrash"; // plasmic-import: VWc3kj67KFnJ/icon
import ClockIcon from "./icons/PlasmicIcon__Clock"; // plasmic-import: dqr28RDSI9p9/icon
import ChevronUpIcon from "./icons/PlasmicIcon__ChevronUp"; // plasmic-import: mpVHKLiWHnf7/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: phBLxJ4vlRyi/icon
import DownloadIcon from "./icons/PlasmicIcon__Download"; // plasmic-import: QcKmgMaHPSAz/icon

export type PlasmicEventListItem__VariantMembers = {
  showingDetails: "showingDetails";
};
export type PlasmicEventListItem__VariantsArgs = {
  showingDetails?: SingleBooleanChoiceArg<"showingDetails">;
};
type VariantPropType = keyof PlasmicEventListItem__VariantsArgs;
export const PlasmicEventListItem__VariantProps = new Array<VariantPropType>(
  "showingDetails"
);

export type PlasmicEventListItem__ArgsType = {
  name?: string;
  participantsCount?: number;
  collectedWasteAmount?: number;
  duration?: number;
  slotWasteListContainer?: React.ReactNode;
  dateBegan?: string;
  dateEnded?: string;
};
type ArgPropType = keyof PlasmicEventListItem__ArgsType;
export const PlasmicEventListItem__ArgProps = new Array<ArgPropType>(
  "name",
  "participantsCount",
  "collectedWasteAmount",
  "duration",
  "slotWasteListContainer",
  "dateBegan",
  "dateEnded"
);

export type PlasmicEventListItem__OverridesType = {
  eventListItem?: Flex__<"div">;
  eventListItemHeader?: Flex__<"div">;
  eventListItemInfoContainer?: Flex__<"div">;
  eventName?: Flex__<"h1">;
  eventDate?: Flex__<"div">;
  eventListItemStatsContainer?: Flex__<"div">;
  eventListItemParticipantsStat?: Flex__<"div">;
  eventListItemParticipantsStatValueLabel?: Flex__<"h1">;
  eventListItemParticipantsStatLabel?: Flex__<"h1">;
  eventListItemCollectedWasteStat?: Flex__<"div">;
  eventListItemCollectedWasteStatValueLabel?: Flex__<"h1">;
  eventListItemCollectedStatWasteLabel?: Flex__<"h1">;
  eventListItemTimeStat?: Flex__<"div">;
  eventListItemTimeStatValueLabel?: Flex__<"h1">;
  eventListItemTimeStatLabel?: Flex__<"h1">;
  eventListItemDetailsButton?: Flex__<"button">;
  eventListItemDetailsContainer?: Flex__<"div">;
  eventListItemMapContainer?: Flex__<"div">;
  interactiveMap?: Flex__<typeof InteractiveMap>;
  eventListItemDataDownloadOptions?: Flex__<"div">;
  eventListItemDownloadCsvButton?: Flex__<"button">;
  eventListItemDownloadJsonButton?: Flex__<"button">;
  eventListItemWasteDataContainer?: Flex__<"div">;
  wasteListTitle?: Flex__<"div">;
  h4?: Flex__<"h4">;
  noData?: Flex__<"h4">;
  wasteListContainer?: Flex__<"div">;
};

export interface DefaultEventListItemProps {
  name?: string;
  participantsCount?: number;
  collectedWasteAmount?: number;
  duration?: number;
  slotWasteListContainer?: React.ReactNode;
  dateBegan?: string;
  dateEnded?: string;
  showingDetails?: SingleBooleanChoiceArg<"showingDetails">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicEventListItem__RenderFunc(props: {
  variants: PlasmicEventListItem__VariantsArgs;
  args: PlasmicEventListItem__ArgsType;
  overrides: PlasmicEventListItem__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          participantsCount: 0,
          collectedWasteAmount: 0,
          duration: 0
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "showingDetails",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.showingDetails
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"eventListItem"}
      data-plasmic-override={overrides.eventListItem}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.eventListItem,
        {
          [sty.eventListItemshowingDetails]: hasVariant(
            $state,
            "showingDetails",
            "showingDetails"
          )
        }
      )}
    >
      <div
        data-plasmic-name={"eventListItemHeader"}
        data-plasmic-override={overrides.eventListItemHeader}
        className={classNames("all", sty.eventListItemHeader)}
      >
        <CalendarIcon
          className={classNames("all", sty.svg__vlZTy)}
          role={"img"}
        />

        <div
          data-plasmic-name={"eventListItemInfoContainer"}
          data-plasmic-override={overrides.eventListItemInfoContainer}
          className={classNames("all", sty.eventListItemInfoContainer)}
        >
          <h1
            data-plasmic-name={"eventName"}
            data-plasmic-override={overrides.eventName}
            className={classNames("all", "h1", "h1__6FNNC", sty.eventName, {
              [sty.eventNameshowingDetails]: hasVariant(
                $state,
                "showingDetails",
                "showingDetails"
              )
            })}
          >
            <div className={classNames("all", "__wab_text", sty.text___5Bk7M)}>
              <React.Fragment>
                {(() => {
                  try {
                    return $props.name;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "Event Name";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </h1>
          <div
            data-plasmic-name={"eventDate"}
            data-plasmic-override={overrides.eventDate}
            className={classNames("all", sty.eventDate, {
              [sty.eventDateshowingDetails]: hasVariant(
                $state,
                "showingDetails",
                "showingDetails"
              )
            })}
          >
            <div
              className={classNames("all", "__wab_text", sty.text___47TuG, {
                [sty.textshowingDetails___47TuGyiMgY]: hasVariant(
                  $state,
                  "showingDetails",
                  "showingDetails"
                )
              })}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $props.dateBegan + " \u2022 " + $props.dateEnded;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "...";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
            <div
              className={classNames("all", "__wab_text", sty.text__ixsR, {
                [sty.textshowingDetails__ixsRYiMgY]: hasVariant(
                  $state,
                  "showingDetails",
                  "showingDetails"
                )
              })}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $props.dateBegan + "\n" + $props.dateEnded;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "...";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </div>
        </div>
      </div>
      <div
        data-plasmic-name={"eventListItemStatsContainer"}
        data-plasmic-override={overrides.eventListItemStatsContainer}
        className={classNames("all", sty.eventListItemStatsContainer, {
          [sty.eventListItemStatsContainershowingDetails]: hasVariant(
            $state,
            "showingDetails",
            "showingDetails"
          )
        })}
      >
        <div
          data-plasmic-name={"eventListItemParticipantsStat"}
          data-plasmic-override={overrides.eventListItemParticipantsStat}
          className={classNames("all", sty.eventListItemParticipantsStat)}
        >
          <PeopleIcon
            className={classNames("all", sty.svg__yijWq)}
            role={"img"}
          />

          <h1
            data-plasmic-name={"eventListItemParticipantsStatValueLabel"}
            data-plasmic-override={
              overrides.eventListItemParticipantsStatValueLabel
            }
            className={classNames(
              "all",
              "h1",
              "h1__6FNNC",
              sty.eventListItemParticipantsStatValueLabel
            )}
          >
            <div className={classNames("all", "__wab_text", sty.text__vAviY)}>
              <React.Fragment>
                {(() => {
                  try {
                    return $props.participantsCount;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "0";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </h1>
          <h1
            data-plasmic-name={"eventListItemParticipantsStatLabel"}
            data-plasmic-override={overrides.eventListItemParticipantsStatLabel}
            className={classNames(
              "all",
              "h1",
              "h1__6FNNC",
              "__wab_text",
              sty.eventListItemParticipantsStatLabel
            )}
          >
            {"participants"}
          </h1>
        </div>
        <div
          data-plasmic-name={"eventListItemCollectedWasteStat"}
          data-plasmic-override={overrides.eventListItemCollectedWasteStat}
          className={classNames("all", sty.eventListItemCollectedWasteStat)}
        >
          <MovingTrashIcon
            className={classNames("all", sty.svg__fr3PL)}
            role={"img"}
          />

          <h1
            data-plasmic-name={"eventListItemCollectedWasteStatValueLabel"}
            data-plasmic-override={
              overrides.eventListItemCollectedWasteStatValueLabel
            }
            className={classNames(
              "all",
              "h1",
              "h1__6FNNC",
              sty.eventListItemCollectedWasteStatValueLabel
            )}
          >
            <div className={classNames("all", "__wab_text", sty.text__yGFjp)}>
              <React.Fragment>
                {(() => {
                  try {
                    return $props.collectedWasteAmount;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "0";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </h1>
          <h1
            data-plasmic-name={"eventListItemCollectedStatWasteLabel"}
            data-plasmic-override={
              overrides.eventListItemCollectedStatWasteLabel
            }
            className={classNames(
              "all",
              "h1",
              "h1__6FNNC",
              "__wab_text",
              sty.eventListItemCollectedStatWasteLabel
            )}
          >
            {"collected waste items"}
          </h1>
        </div>
        <div
          data-plasmic-name={"eventListItemTimeStat"}
          data-plasmic-override={overrides.eventListItemTimeStat}
          className={classNames("all", sty.eventListItemTimeStat)}
        >
          <ClockIcon
            className={classNames("all", sty.svg__fky8L)}
            role={"img"}
          />

          <h1
            data-plasmic-name={"eventListItemTimeStatValueLabel"}
            data-plasmic-override={overrides.eventListItemTimeStatValueLabel}
            className={classNames(
              "all",
              "h1",
              "h1__6FNNC",
              sty.eventListItemTimeStatValueLabel
            )}
          >
            <div className={classNames("all", "__wab_text", sty.text__yHkfn)}>
              <React.Fragment>
                {(() => {
                  try {
                    return $props.duration;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "0";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </h1>
          <h1
            data-plasmic-name={"eventListItemTimeStatLabel"}
            data-plasmic-override={overrides.eventListItemTimeStatLabel}
            className={classNames(
              "all",
              "h1",
              "h1__6FNNC",
              "__wab_text",
              sty.eventListItemTimeStatLabel
            )}
          >
            {"hours"}
          </h1>
        </div>
      </div>
      <button
        data-plasmic-name={"eventListItemDetailsButton"}
        data-plasmic-override={overrides.eventListItemDetailsButton}
        className={classNames(
          "all",
          "button",
          "button__6FNNC",
          sty.eventListItemDetailsButton
        )}
        onClick={async event => {
          const $steps = {};

          $steps["updateShowingDetails"] = true
            ? (() => {
                const actionArgs = { vgroup: "showingDetails", operation: 2 };
                return (({ vgroup, value }) => {
                  if (typeof value === "string") {
                    value = [value];
                  }

                  const oldValue = $stateGet($state, vgroup);
                  $stateSet($state, vgroup, !oldValue);
                  return !oldValue;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateShowingDetails"] != null &&
            typeof $steps["updateShowingDetails"] === "object" &&
            typeof $steps["updateShowingDetails"].then === "function"
          ) {
            $steps["updateShowingDetails"] =
              await $steps["updateShowingDetails"];
          }
        }}
        ref={ref => {
          $refs["eventListItemDetailsButton"] = ref;
        }}
      >
        <PlasmicIcon__
          PlasmicIconType={
            hasVariant($state, "showingDetails", "showingDetails")
              ? ChevronDownIcon
              : ChevronUpIcon
          }
          className={classNames("all", sty.svg___59Ke8, {
            [sty.svgshowingDetails___59Ke8YiMgY]: hasVariant(
              $state,
              "showingDetails",
              "showingDetails"
            )
          })}
          role={"img"}
        />

        <div className={classNames("all", "__wab_text", sty.text__qsgQl)}>
          {"Event Details"}
        </div>
      </button>
      <div
        data-plasmic-name={"eventListItemDetailsContainer"}
        data-plasmic-override={overrides.eventListItemDetailsContainer}
        className={classNames("all", sty.eventListItemDetailsContainer, {
          [sty.eventListItemDetailsContainershowingDetails]: hasVariant(
            $state,
            "showingDetails",
            "showingDetails"
          )
        })}
      >
        <div
          data-plasmic-name={"eventListItemMapContainer"}
          data-plasmic-override={overrides.eventListItemMapContainer}
          className={classNames("all", sty.eventListItemMapContainer)}
        >
          <InteractiveMap
            data-plasmic-name={"interactiveMap"}
            data-plasmic-override={overrides.interactiveMap}
            className={classNames("__wab_instance", sty.interactiveMap)}
          />

          <div
            data-plasmic-name={"eventListItemDataDownloadOptions"}
            data-plasmic-override={overrides.eventListItemDataDownloadOptions}
            className={classNames("all", sty.eventListItemDataDownloadOptions)}
          >
            <button
              data-plasmic-name={"eventListItemDownloadCsvButton"}
              data-plasmic-override={overrides.eventListItemDownloadCsvButton}
              className={classNames(
                "all",
                "button",
                "button__6FNNC",
                sty.eventListItemDownloadCsvButton
              )}
              onClick={async event => {
                const $steps = {};
              }}
              ref={ref => {
                $refs["eventListItemDownloadCsvButton"] = ref;
              }}
            >
              <DownloadIcon
                className={classNames("all", sty.svg___32HqH)}
                role={"img"}
              />

              <div className={classNames("all", "__wab_text", sty.text__lAvTp)}>
                {"Download CSV"}
              </div>
              <div className={classNames("all", "__wab_text", sty.text__jHWc1)}>
                {hasVariant(globalVariants, "screen", "mobile") ? "CSV" : "CSV"}
              </div>
            </button>
            <button
              data-plasmic-name={"eventListItemDownloadJsonButton"}
              data-plasmic-override={overrides.eventListItemDownloadJsonButton}
              className={classNames(
                "all",
                "button",
                "button__6FNNC",
                sty.eventListItemDownloadJsonButton
              )}
              onClick={async event => {
                const $steps = {};

                $steps["updateStateVariable"] = true
                  ? (() => {
                      const actionArgs = {};
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;
                        undefined;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateStateVariable"] != null &&
                  typeof $steps["updateStateVariable"] === "object" &&
                  typeof $steps["updateStateVariable"].then === "function"
                ) {
                  $steps["updateStateVariable"] =
                    await $steps["updateStateVariable"];
                }
              }}
              ref={ref => {
                $refs["eventListItemDownloadJsonButton"] = ref;
              }}
            >
              <DownloadIcon
                className={classNames("all", sty.svg__oSup9)}
                role={"img"}
              />

              <div className={classNames("all", "__wab_text", sty.text__gYovT)}>
                {"Download JSON"}
              </div>
              <div className={classNames("all", "__wab_text", sty.text__z06Tf)}>
                {hasVariant(globalVariants, "screen", "mobile")
                  ? "JSON"
                  : "JSON"}
              </div>
            </button>
          </div>
        </div>
        <div
          data-plasmic-name={"eventListItemWasteDataContainer"}
          data-plasmic-override={overrides.eventListItemWasteDataContainer}
          className={classNames("all", sty.eventListItemWasteDataContainer)}
        >
          <div
            data-plasmic-name={"wasteListTitle"}
            data-plasmic-override={overrides.wasteListTitle}
            className={classNames("all", "__wab_text", sty.wasteListTitle)}
          >
            {hasVariant(globalVariants, "screen", "mobile") ? (
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h4
                    data-plasmic-name={"h4"}
                    data-plasmic-override={overrides.h4}
                    className={classNames(
                      "all",
                      "h4",
                      "h4__6FNNC",
                      "__wab_text",
                      sty.h4
                    )}
                  >
                    {"Top Waste Types\r"}
                  </h4>
                }
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            ) : (
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h4
                    data-plasmic-name={"h4"}
                    data-plasmic-override={overrides.h4}
                    className={classNames(
                      "all",
                      "h4",
                      "h4__6FNNC",
                      "__wab_text",
                      sty.h4
                    )}
                  >
                    {"Top Waste Types\r"}
                  </h4>
                }
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            )}
          </div>
          <h4
            data-plasmic-name={"noData"}
            data-plasmic-override={overrides.noData}
            className={classNames(
              "all",
              "h4",
              "h4__6FNNC",
              "__wab_text",
              sty.noData
            )}
          >
            {"No Data :("}
          </h4>
          <div
            data-plasmic-name={"wasteListContainer"}
            data-plasmic-override={overrides.wasteListContainer}
            className={classNames("all", sty.wasteListContainer)}
          >
            {renderPlasmicSlot({
              defaultContents: null,
              value: args.slotWasteListContainer
            })}
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  eventListItem: [
    "eventListItem",
    "eventListItemHeader",
    "eventListItemInfoContainer",
    "eventName",
    "eventDate",
    "eventListItemStatsContainer",
    "eventListItemParticipantsStat",
    "eventListItemParticipantsStatValueLabel",
    "eventListItemParticipantsStatLabel",
    "eventListItemCollectedWasteStat",
    "eventListItemCollectedWasteStatValueLabel",
    "eventListItemCollectedStatWasteLabel",
    "eventListItemTimeStat",
    "eventListItemTimeStatValueLabel",
    "eventListItemTimeStatLabel",
    "eventListItemDetailsButton",
    "eventListItemDetailsContainer",
    "eventListItemMapContainer",
    "interactiveMap",
    "eventListItemDataDownloadOptions",
    "eventListItemDownloadCsvButton",
    "eventListItemDownloadJsonButton",
    "eventListItemWasteDataContainer",
    "wasteListTitle",
    "h4",
    "noData",
    "wasteListContainer"
  ],
  eventListItemHeader: [
    "eventListItemHeader",
    "eventListItemInfoContainer",
    "eventName",
    "eventDate"
  ],
  eventListItemInfoContainer: [
    "eventListItemInfoContainer",
    "eventName",
    "eventDate"
  ],
  eventName: ["eventName"],
  eventDate: ["eventDate"],
  eventListItemStatsContainer: [
    "eventListItemStatsContainer",
    "eventListItemParticipantsStat",
    "eventListItemParticipantsStatValueLabel",
    "eventListItemParticipantsStatLabel",
    "eventListItemCollectedWasteStat",
    "eventListItemCollectedWasteStatValueLabel",
    "eventListItemCollectedStatWasteLabel",
    "eventListItemTimeStat",
    "eventListItemTimeStatValueLabel",
    "eventListItemTimeStatLabel"
  ],
  eventListItemParticipantsStat: [
    "eventListItemParticipantsStat",
    "eventListItemParticipantsStatValueLabel",
    "eventListItemParticipantsStatLabel"
  ],
  eventListItemParticipantsStatValueLabel: [
    "eventListItemParticipantsStatValueLabel"
  ],
  eventListItemParticipantsStatLabel: ["eventListItemParticipantsStatLabel"],
  eventListItemCollectedWasteStat: [
    "eventListItemCollectedWasteStat",
    "eventListItemCollectedWasteStatValueLabel",
    "eventListItemCollectedStatWasteLabel"
  ],
  eventListItemCollectedWasteStatValueLabel: [
    "eventListItemCollectedWasteStatValueLabel"
  ],
  eventListItemCollectedStatWasteLabel: [
    "eventListItemCollectedStatWasteLabel"
  ],
  eventListItemTimeStat: [
    "eventListItemTimeStat",
    "eventListItemTimeStatValueLabel",
    "eventListItemTimeStatLabel"
  ],
  eventListItemTimeStatValueLabel: ["eventListItemTimeStatValueLabel"],
  eventListItemTimeStatLabel: ["eventListItemTimeStatLabel"],
  eventListItemDetailsButton: ["eventListItemDetailsButton"],
  eventListItemDetailsContainer: [
    "eventListItemDetailsContainer",
    "eventListItemMapContainer",
    "interactiveMap",
    "eventListItemDataDownloadOptions",
    "eventListItemDownloadCsvButton",
    "eventListItemDownloadJsonButton",
    "eventListItemWasteDataContainer",
    "wasteListTitle",
    "h4",
    "noData",
    "wasteListContainer"
  ],
  eventListItemMapContainer: [
    "eventListItemMapContainer",
    "interactiveMap",
    "eventListItemDataDownloadOptions",
    "eventListItemDownloadCsvButton",
    "eventListItemDownloadJsonButton"
  ],
  interactiveMap: ["interactiveMap"],
  eventListItemDataDownloadOptions: [
    "eventListItemDataDownloadOptions",
    "eventListItemDownloadCsvButton",
    "eventListItemDownloadJsonButton"
  ],
  eventListItemDownloadCsvButton: ["eventListItemDownloadCsvButton"],
  eventListItemDownloadJsonButton: ["eventListItemDownloadJsonButton"],
  eventListItemWasteDataContainer: [
    "eventListItemWasteDataContainer",
    "wasteListTitle",
    "h4",
    "noData",
    "wasteListContainer"
  ],
  wasteListTitle: ["wasteListTitle", "h4"],
  h4: ["h4"],
  noData: ["noData"],
  wasteListContainer: ["wasteListContainer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  eventListItem: "div";
  eventListItemHeader: "div";
  eventListItemInfoContainer: "div";
  eventName: "h1";
  eventDate: "div";
  eventListItemStatsContainer: "div";
  eventListItemParticipantsStat: "div";
  eventListItemParticipantsStatValueLabel: "h1";
  eventListItemParticipantsStatLabel: "h1";
  eventListItemCollectedWasteStat: "div";
  eventListItemCollectedWasteStatValueLabel: "h1";
  eventListItemCollectedStatWasteLabel: "h1";
  eventListItemTimeStat: "div";
  eventListItemTimeStatValueLabel: "h1";
  eventListItemTimeStatLabel: "h1";
  eventListItemDetailsButton: "button";
  eventListItemDetailsContainer: "div";
  eventListItemMapContainer: "div";
  interactiveMap: typeof InteractiveMap;
  eventListItemDataDownloadOptions: "div";
  eventListItemDownloadCsvButton: "button";
  eventListItemDownloadJsonButton: "button";
  eventListItemWasteDataContainer: "div";
  wasteListTitle: "div";
  h4: "h4";
  noData: "h4";
  wasteListContainer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicEventListItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicEventListItem__VariantsArgs;
    args?: PlasmicEventListItem__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicEventListItem__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicEventListItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicEventListItem__ArgProps,
          internalVariantPropNames: PlasmicEventListItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicEventListItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "eventListItem") {
    func.displayName = "PlasmicEventListItem";
  } else {
    func.displayName = `PlasmicEventListItem.${nodeName}`;
  }
  return func;
}

export const PlasmicEventListItem = Object.assign(
  // Top-level PlasmicEventListItem renders the root element
  makeNodeComponent("eventListItem"),
  {
    // Helper components rendering sub-elements
    eventListItemHeader: makeNodeComponent("eventListItemHeader"),
    eventListItemInfoContainer: makeNodeComponent("eventListItemInfoContainer"),
    eventName: makeNodeComponent("eventName"),
    eventDate: makeNodeComponent("eventDate"),
    eventListItemStatsContainer: makeNodeComponent(
      "eventListItemStatsContainer"
    ),
    eventListItemParticipantsStat: makeNodeComponent(
      "eventListItemParticipantsStat"
    ),
    eventListItemParticipantsStatValueLabel: makeNodeComponent(
      "eventListItemParticipantsStatValueLabel"
    ),
    eventListItemParticipantsStatLabel: makeNodeComponent(
      "eventListItemParticipantsStatLabel"
    ),
    eventListItemCollectedWasteStat: makeNodeComponent(
      "eventListItemCollectedWasteStat"
    ),
    eventListItemCollectedWasteStatValueLabel: makeNodeComponent(
      "eventListItemCollectedWasteStatValueLabel"
    ),
    eventListItemCollectedStatWasteLabel: makeNodeComponent(
      "eventListItemCollectedStatWasteLabel"
    ),
    eventListItemTimeStat: makeNodeComponent("eventListItemTimeStat"),
    eventListItemTimeStatValueLabel: makeNodeComponent(
      "eventListItemTimeStatValueLabel"
    ),
    eventListItemTimeStatLabel: makeNodeComponent("eventListItemTimeStatLabel"),
    eventListItemDetailsButton: makeNodeComponent("eventListItemDetailsButton"),
    eventListItemDetailsContainer: makeNodeComponent(
      "eventListItemDetailsContainer"
    ),
    eventListItemMapContainer: makeNodeComponent("eventListItemMapContainer"),
    interactiveMap: makeNodeComponent("interactiveMap"),
    eventListItemDataDownloadOptions: makeNodeComponent(
      "eventListItemDataDownloadOptions"
    ),
    eventListItemDownloadCsvButton: makeNodeComponent(
      "eventListItemDownloadCsvButton"
    ),
    eventListItemDownloadJsonButton: makeNodeComponent(
      "eventListItemDownloadJsonButton"
    ),
    eventListItemWasteDataContainer: makeNodeComponent(
      "eventListItemWasteDataContainer"
    ),
    wasteListTitle: makeNodeComponent("wasteListTitle"),
    h4: makeNodeComponent("h4"),
    noData: makeNodeComponent("noData"),
    wasteListContainer: makeNodeComponent("wasteListContainer"),

    // Metadata about props expected for PlasmicEventListItem
    internalVariantProps: PlasmicEventListItem__VariantProps,
    internalArgProps: PlasmicEventListItem__ArgProps
  }
);

export default PlasmicEventListItem;
/* prettier-ignore-end */
