/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: -j03wg22fnSS

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicEventWasteTypeListItem.module.css"; // plasmic-import: -j03wg22fnSS/css

export type PlasmicEventWasteTypeListItem__VariantMembers = {};
export type PlasmicEventWasteTypeListItem__VariantsArgs = {};
type VariantPropType = keyof PlasmicEventWasteTypeListItem__VariantsArgs;
export const PlasmicEventWasteTypeListItem__VariantProps =
  new Array<VariantPropType>();

export type PlasmicEventWasteTypeListItem__ArgsType = {
  wasteType?: string;
  amount?: number;
};
type ArgPropType = keyof PlasmicEventWasteTypeListItem__ArgsType;
export const PlasmicEventWasteTypeListItem__ArgProps = new Array<ArgPropType>(
  "wasteType",
  "amount"
);

export type PlasmicEventWasteTypeListItem__OverridesType = {
  eventWasteTypeListItem?: Flex__<"div">;
  wasteTypeAmountLabel?: Flex__<"h4">;
  wasteTypeNameLabel?: Flex__<"h4">;
};

export interface DefaultEventWasteTypeListItemProps {
  wasteType?: string;
  amount?: number;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicEventWasteTypeListItem__RenderFunc(props: {
  variants: PlasmicEventWasteTypeListItem__VariantsArgs;
  args: PlasmicEventWasteTypeListItem__ArgsType;
  overrides: PlasmicEventWasteTypeListItem__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          wasteType: "Unknown",
          amount: 0
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"eventWasteTypeListItem"}
      data-plasmic-override={overrides.eventWasteTypeListItem}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.eventWasteTypeListItem
      )}
    >
      <h4
        data-plasmic-name={"wasteTypeAmountLabel"}
        data-plasmic-override={overrides.wasteTypeAmountLabel}
        className={classNames(
          "all",
          "h4",
          "h4__6FNNC",
          "__wab_text",
          sty.wasteTypeAmountLabel
        )}
      >
        <React.Fragment>
          {(() => {
            try {
              return $props.amount;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "0";
              }
              throw e;
            }
          })()}
        </React.Fragment>
      </h4>
      <h4
        data-plasmic-name={"wasteTypeNameLabel"}
        data-plasmic-override={overrides.wasteTypeNameLabel}
        className={classNames(
          "all",
          "h4",
          "h4__6FNNC",
          "__wab_text",
          sty.wasteTypeNameLabel
        )}
      >
        <React.Fragment>
          {(() => {
            try {
              return $props.wasteType;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "Waste Type";
              }
              throw e;
            }
          })()}
        </React.Fragment>
      </h4>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  eventWasteTypeListItem: [
    "eventWasteTypeListItem",
    "wasteTypeAmountLabel",
    "wasteTypeNameLabel"
  ],
  wasteTypeAmountLabel: ["wasteTypeAmountLabel"],
  wasteTypeNameLabel: ["wasteTypeNameLabel"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  eventWasteTypeListItem: "div";
  wasteTypeAmountLabel: "h4";
  wasteTypeNameLabel: "h4";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicEventWasteTypeListItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicEventWasteTypeListItem__VariantsArgs;
    args?: PlasmicEventWasteTypeListItem__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicEventWasteTypeListItem__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicEventWasteTypeListItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicEventWasteTypeListItem__ArgProps,
          internalVariantPropNames: PlasmicEventWasteTypeListItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicEventWasteTypeListItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "eventWasteTypeListItem") {
    func.displayName = "PlasmicEventWasteTypeListItem";
  } else {
    func.displayName = `PlasmicEventWasteTypeListItem.${nodeName}`;
  }
  return func;
}

export const PlasmicEventWasteTypeListItem = Object.assign(
  // Top-level PlasmicEventWasteTypeListItem renders the root element
  makeNodeComponent("eventWasteTypeListItem"),
  {
    // Helper components rendering sub-elements
    wasteTypeAmountLabel: makeNodeComponent("wasteTypeAmountLabel"),
    wasteTypeNameLabel: makeNodeComponent("wasteTypeNameLabel"),

    // Metadata about props expected for PlasmicEventWasteTypeListItem
    internalVariantProps: PlasmicEventWasteTypeListItem__VariantProps,
    internalArgProps: PlasmicEventWasteTypeListItem__ArgProps
  }
);

export default PlasmicEventWasteTypeListItem;
/* prettier-ignore-end */
