/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: EnVcSZGZQy5n

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NavigationBar from "../../NavigationBar"; // plasmic-import: 9ar3kGz7iBUD/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicProfile.module.css"; // plasmic-import: EnVcSZGZQy5n/css

import ProfileIcon from "./icons/PlasmicIcon__Profile"; // plasmic-import: OkMjqJNO-au2/icon
import TriangleFilledIcon from "./icons/PlasmicIcon__TriangleFilled"; // plasmic-import: 31rbojHD3Acy/icon
import MovingTrashIcon from "./icons/PlasmicIcon__MovingTrash"; // plasmic-import: VWc3kj67KFnJ/icon
import ClockIcon from "./icons/PlasmicIcon__Clock"; // plasmic-import: dqr28RDSI9p9/icon
import ExitIcon from "./icons/PlasmicIcon__Exit"; // plasmic-import: ls_1Bif9RNoB/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "My Profile",

    openGraph: {
      title: "My Profile",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    },
    twitter: {
      card: "summary_large_image" as const,
      title: "My Profile",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    }
  };
}

export type PlasmicProfile__VariantMembers = {};
export type PlasmicProfile__VariantsArgs = {};
type VariantPropType = keyof PlasmicProfile__VariantsArgs;
export const PlasmicProfile__VariantProps = new Array<VariantPropType>();

export type PlasmicProfile__ArgsType = {};
type ArgPropType = keyof PlasmicProfile__ArgsType;
export const PlasmicProfile__ArgProps = new Array<ArgPropType>();

export type PlasmicProfile__OverridesType = {
  profilePage?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  profileContainer?: Flex__<"div">;
  profileHeader?: Flex__<"div">;
  profileInfoContainer?: Flex__<"div">;
  profileUserNameLabel?: Flex__<"h1">;
  profileJoinDateLabel?: Flex__<"div">;
  profileStatsContainer?: Flex__<"div">;
  pointsStatContainer?: Flex__<"div">;
  pointsStatValueLabel?: Flex__<"h1">;
  pointsStatLabel?: Flex__<"h1">;
  collectedWasteStatContainer?: Flex__<"div">;
  collectedWasteStatValueLabel?: Flex__<"h1">;
  collectedWasteStatLabel?: Flex__<"h1">;
  totalHoursStatContainer?: Flex__<"div">;
  totalHoursStatValueLabel?: Flex__<"h1">;
  totalHoursStatLabel?: Flex__<"h1">;
  logOutButton?: Flex__<"button">;
  text?: Flex__<"div">;
  leaderboardContainer?: Flex__<"div">;
  leaderboardTitle?: Flex__<"h1">;
  leaderboardListContainer?: Flex__<"div">;
};

export interface DefaultProfileProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProfile__RenderFunc(props: {
  variants: PlasmicProfile__VariantsArgs;
  args: PlasmicProfile__ArgsType;
  overrides: PlasmicProfile__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"profilePage"}
          data-plasmic-override={overrides.profilePage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.profilePage
          )}
        >
          <NavigationBar
            data-plasmic-name={"navigationBar"}
            data-plasmic-override={overrides.navigationBar}
            className={classNames("__wab_instance", sty.navigationBar)}
            tab={"profile"}
          />

          <div
            data-plasmic-name={"profileContainer"}
            data-plasmic-override={overrides.profileContainer}
            className={classNames("all", sty.profileContainer)}
          >
            <div
              data-plasmic-name={"profileHeader"}
              data-plasmic-override={overrides.profileHeader}
              className={classNames("all", sty.profileHeader)}
            >
              <ProfileIcon
                className={classNames("all", sty.svg__bmB)}
                role={"img"}
              />

              <div
                data-plasmic-name={"profileInfoContainer"}
                data-plasmic-override={overrides.profileInfoContainer}
                className={classNames("all", sty.profileInfoContainer)}
              >
                <h1
                  data-plasmic-name={"profileUserNameLabel"}
                  data-plasmic-override={overrides.profileUserNameLabel}
                  className={classNames(
                    "all",
                    "h1",
                    "h1__6FNNC",
                    "__wab_text",
                    sty.profileUserNameLabel
                  )}
                >
                  {"User Name"}
                </h1>
                <div
                  data-plasmic-name={"profileJoinDateLabel"}
                  data-plasmic-override={overrides.profileJoinDateLabel}
                  className={classNames(
                    "all",
                    "__wab_text",
                    sty.profileJoinDateLabel
                  )}
                >
                  {"Joined XXXX-XX-XX\n\r"}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"profileStatsContainer"}
              data-plasmic-override={overrides.profileStatsContainer}
              className={classNames("all", sty.profileStatsContainer)}
            >
              <div
                data-plasmic-name={"pointsStatContainer"}
                data-plasmic-override={overrides.pointsStatContainer}
                className={classNames("all", sty.pointsStatContainer)}
              >
                <TriangleFilledIcon
                  className={classNames("all", sty.svg__jFjsG)}
                  role={"img"}
                />

                <h1
                  data-plasmic-name={"pointsStatValueLabel"}
                  data-plasmic-override={overrides.pointsStatValueLabel}
                  className={classNames(
                    "all",
                    "h1",
                    "h1__6FNNC",
                    "__wab_text",
                    sty.pointsStatValueLabel
                  )}
                >
                  {"0"}
                </h1>
                <h1
                  data-plasmic-name={"pointsStatLabel"}
                  data-plasmic-override={overrides.pointsStatLabel}
                  className={classNames(
                    "all",
                    "h1",
                    "h1__6FNNC",
                    "__wab_text",
                    sty.pointsStatLabel
                  )}
                >
                  {"points"}
                </h1>
              </div>
              <div
                data-plasmic-name={"collectedWasteStatContainer"}
                data-plasmic-override={overrides.collectedWasteStatContainer}
                className={classNames("all", sty.collectedWasteStatContainer)}
              >
                <MovingTrashIcon
                  className={classNames("all", sty.svg__sczzt)}
                  role={"img"}
                />

                <h1
                  data-plasmic-name={"collectedWasteStatValueLabel"}
                  data-plasmic-override={overrides.collectedWasteStatValueLabel}
                  className={classNames(
                    "all",
                    "h1",
                    "h1__6FNNC",
                    "__wab_text",
                    sty.collectedWasteStatValueLabel
                  )}
                >
                  {"0"}
                </h1>
                <h1
                  data-plasmic-name={"collectedWasteStatLabel"}
                  data-plasmic-override={overrides.collectedWasteStatLabel}
                  className={classNames(
                    "all",
                    "h1",
                    "h1__6FNNC",
                    "__wab_text",
                    sty.collectedWasteStatLabel
                  )}
                >
                  {"total collected waste"}
                </h1>
              </div>
              <div
                data-plasmic-name={"totalHoursStatContainer"}
                data-plasmic-override={overrides.totalHoursStatContainer}
                className={classNames("all", sty.totalHoursStatContainer)}
              >
                <ClockIcon
                  className={classNames("all", sty.svg___2PvHy)}
                  role={"img"}
                />

                <h1
                  data-plasmic-name={"totalHoursStatValueLabel"}
                  data-plasmic-override={overrides.totalHoursStatValueLabel}
                  className={classNames(
                    "all",
                    "h1",
                    "h1__6FNNC",
                    "__wab_text",
                    sty.totalHoursStatValueLabel
                  )}
                >
                  {"0"}
                </h1>
                <h1
                  data-plasmic-name={"totalHoursStatLabel"}
                  data-plasmic-override={overrides.totalHoursStatLabel}
                  className={classNames(
                    "all",
                    "h1",
                    "h1__6FNNC",
                    "__wab_text",
                    sty.totalHoursStatLabel
                  )}
                >
                  {"total event hours"}
                </h1>
              </div>
            </div>
          </div>
          <button
            data-plasmic-name={"logOutButton"}
            data-plasmic-override={overrides.logOutButton}
            className={classNames(
              "all",
              "button",
              "button__6FNNC",
              sty.logOutButton
            )}
            ref={ref => {
              $refs["logOutButton"] = ref;
            }}
          >
            <ExitIcon
              className={classNames("all", sty.svg__uJxbb)}
              role={"img"}
            />

            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames("all", "__wab_text", sty.text)}
            >
              {"Log Out"}
            </div>
          </button>
          <div
            data-plasmic-name={"leaderboardContainer"}
            data-plasmic-override={overrides.leaderboardContainer}
            className={classNames("all", sty.leaderboardContainer)}
          >
            <h1
              data-plasmic-name={"leaderboardTitle"}
              data-plasmic-override={overrides.leaderboardTitle}
              className={classNames(
                "all",
                "h1",
                "h1__6FNNC",
                "__wab_text",
                sty.leaderboardTitle
              )}
            >
              {"Club Leaderboard"}
            </h1>
            <div
              data-plasmic-name={"leaderboardListContainer"}
              data-plasmic-override={overrides.leaderboardListContainer}
              className={classNames("all", sty.leaderboardListContainer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  profilePage: [
    "profilePage",
    "navigationBar",
    "profileContainer",
    "profileHeader",
    "profileInfoContainer",
    "profileUserNameLabel",
    "profileJoinDateLabel",
    "profileStatsContainer",
    "pointsStatContainer",
    "pointsStatValueLabel",
    "pointsStatLabel",
    "collectedWasteStatContainer",
    "collectedWasteStatValueLabel",
    "collectedWasteStatLabel",
    "totalHoursStatContainer",
    "totalHoursStatValueLabel",
    "totalHoursStatLabel",
    "logOutButton",
    "text",
    "leaderboardContainer",
    "leaderboardTitle",
    "leaderboardListContainer"
  ],
  navigationBar: ["navigationBar"],
  profileContainer: [
    "profileContainer",
    "profileHeader",
    "profileInfoContainer",
    "profileUserNameLabel",
    "profileJoinDateLabel",
    "profileStatsContainer",
    "pointsStatContainer",
    "pointsStatValueLabel",
    "pointsStatLabel",
    "collectedWasteStatContainer",
    "collectedWasteStatValueLabel",
    "collectedWasteStatLabel",
    "totalHoursStatContainer",
    "totalHoursStatValueLabel",
    "totalHoursStatLabel"
  ],
  profileHeader: [
    "profileHeader",
    "profileInfoContainer",
    "profileUserNameLabel",
    "profileJoinDateLabel"
  ],
  profileInfoContainer: [
    "profileInfoContainer",
    "profileUserNameLabel",
    "profileJoinDateLabel"
  ],
  profileUserNameLabel: ["profileUserNameLabel"],
  profileJoinDateLabel: ["profileJoinDateLabel"],
  profileStatsContainer: [
    "profileStatsContainer",
    "pointsStatContainer",
    "pointsStatValueLabel",
    "pointsStatLabel",
    "collectedWasteStatContainer",
    "collectedWasteStatValueLabel",
    "collectedWasteStatLabel",
    "totalHoursStatContainer",
    "totalHoursStatValueLabel",
    "totalHoursStatLabel"
  ],
  pointsStatContainer: [
    "pointsStatContainer",
    "pointsStatValueLabel",
    "pointsStatLabel"
  ],
  pointsStatValueLabel: ["pointsStatValueLabel"],
  pointsStatLabel: ["pointsStatLabel"],
  collectedWasteStatContainer: [
    "collectedWasteStatContainer",
    "collectedWasteStatValueLabel",
    "collectedWasteStatLabel"
  ],
  collectedWasteStatValueLabel: ["collectedWasteStatValueLabel"],
  collectedWasteStatLabel: ["collectedWasteStatLabel"],
  totalHoursStatContainer: [
    "totalHoursStatContainer",
    "totalHoursStatValueLabel",
    "totalHoursStatLabel"
  ],
  totalHoursStatValueLabel: ["totalHoursStatValueLabel"],
  totalHoursStatLabel: ["totalHoursStatLabel"],
  logOutButton: ["logOutButton", "text"],
  text: ["text"],
  leaderboardContainer: [
    "leaderboardContainer",
    "leaderboardTitle",
    "leaderboardListContainer"
  ],
  leaderboardTitle: ["leaderboardTitle"],
  leaderboardListContainer: ["leaderboardListContainer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  profilePage: "div";
  navigationBar: typeof NavigationBar;
  profileContainer: "div";
  profileHeader: "div";
  profileInfoContainer: "div";
  profileUserNameLabel: "h1";
  profileJoinDateLabel: "div";
  profileStatsContainer: "div";
  pointsStatContainer: "div";
  pointsStatValueLabel: "h1";
  pointsStatLabel: "h1";
  collectedWasteStatContainer: "div";
  collectedWasteStatValueLabel: "h1";
  collectedWasteStatLabel: "h1";
  totalHoursStatContainer: "div";
  totalHoursStatValueLabel: "h1";
  totalHoursStatLabel: "h1";
  logOutButton: "button";
  text: "div";
  leaderboardContainer: "div";
  leaderboardTitle: "h1";
  leaderboardListContainer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProfile__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProfile__VariantsArgs;
    args?: PlasmicProfile__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicProfile__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicProfile__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProfile__ArgProps,
          internalVariantPropNames: PlasmicProfile__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProfile__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "profilePage") {
    func.displayName = "PlasmicProfile";
  } else {
    func.displayName = `PlasmicProfile.${nodeName}`;
  }
  return func;
}

export const PlasmicProfile = Object.assign(
  // Top-level PlasmicProfile renders the root element
  makeNodeComponent("profilePage"),
  {
    // Helper components rendering sub-elements
    navigationBar: makeNodeComponent("navigationBar"),
    profileContainer: makeNodeComponent("profileContainer"),
    profileHeader: makeNodeComponent("profileHeader"),
    profileInfoContainer: makeNodeComponent("profileInfoContainer"),
    profileUserNameLabel: makeNodeComponent("profileUserNameLabel"),
    profileJoinDateLabel: makeNodeComponent("profileJoinDateLabel"),
    profileStatsContainer: makeNodeComponent("profileStatsContainer"),
    pointsStatContainer: makeNodeComponent("pointsStatContainer"),
    pointsStatValueLabel: makeNodeComponent("pointsStatValueLabel"),
    pointsStatLabel: makeNodeComponent("pointsStatLabel"),
    collectedWasteStatContainer: makeNodeComponent(
      "collectedWasteStatContainer"
    ),
    collectedWasteStatValueLabel: makeNodeComponent(
      "collectedWasteStatValueLabel"
    ),
    collectedWasteStatLabel: makeNodeComponent("collectedWasteStatLabel"),
    totalHoursStatContainer: makeNodeComponent("totalHoursStatContainer"),
    totalHoursStatValueLabel: makeNodeComponent("totalHoursStatValueLabel"),
    totalHoursStatLabel: makeNodeComponent("totalHoursStatLabel"),
    logOutButton: makeNodeComponent("logOutButton"),
    text: makeNodeComponent("text"),
    leaderboardContainer: makeNodeComponent("leaderboardContainer"),
    leaderboardTitle: makeNodeComponent("leaderboardTitle"),
    leaderboardListContainer: makeNodeComponent("leaderboardListContainer"),

    // Metadata about props expected for PlasmicProfile
    internalVariantProps: PlasmicProfile__VariantProps,
    internalArgProps: PlasmicProfile__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/profile",
      pagePath: "/profile",
      params: {},
      query: {}
    })
  }
);

export default PlasmicProfile;
/* prettier-ignore-end */
