/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: zsUEnI5rKhQz

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Message from "../../Message"; // plasmic-import: bsLCN1wPMRSw/component
import NavigationBar from "../../NavigationBar"; // plasmic-import: 9ar3kGz7iBUD/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicAdminPortal.module.css"; // plasmic-import: zsUEnI5rKhQz/css

import XCloseIcon from "./icons/PlasmicIcon__XClose"; // plasmic-import: R5NpJDhUjGD_/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Admin Portal",

    openGraph: {
      title: "Admin Portal"
    },
    twitter: {
      card: "summary" as const,
      title: "Admin Portal"
    }
  };
}

export type PlasmicAdminPortal__VariantMembers = {};
export type PlasmicAdminPortal__VariantsArgs = {};
type VariantPropType = keyof PlasmicAdminPortal__VariantsArgs;
export const PlasmicAdminPortal__VariantProps = new Array<VariantPropType>();

export type PlasmicAdminPortal__ArgsType = {};
type ArgPropType = keyof PlasmicAdminPortal__ArgsType;
export const PlasmicAdminPortal__ArgProps = new Array<ArgPropType>();

export type PlasmicAdminPortal__OverridesType = {
  adminPortalPage?: Flex__<"div">;
  header?: Flex__<"div">;
  h1?: Flex__<"h1">;
  welcomeMessage?: Flex__<typeof Message>;
  warningMessage?: Flex__<typeof Message>;
  navigationBar?: Flex__<typeof NavigationBar>;
};

export interface DefaultAdminPortalProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAdminPortal__RenderFunc(props: {
  variants: PlasmicAdminPortal__VariantsArgs;
  args: PlasmicAdminPortal__ArgsType;
  overrides: PlasmicAdminPortal__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "introductionRead",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "warningRead",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"adminPortalPage"}
          data-plasmic-override={overrides.adminPortalPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.adminPortalPage
          )}
        >
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("all", sty.header)}
          >
            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                "all",
                "h1",
                "h1__6FNNC",
                "__wab_text",
                sty.h1
              )}
            >
              {"Admin Portal"}
            </h1>
          </div>
          <Message
            data-plasmic-name={"welcomeMessage"}
            data-plasmic-override={overrides.welcomeMessage}
            className={classNames("__wab_instance", sty.welcomeMessage)}
            closeButton2={
              <XCloseIcon
                className={classNames("all", sty.svg__vvmcu)}
                role={"img"}
              />
            }
          >
            <div className={classNames("all", "__wab_text", sty.text__cc2YT)}>
              <React.Fragment>
                <React.Fragment>{"Welcome to the "}</React.Fragment>
                <span
                  className={
                    "plasmic_default__all plasmic_default__span plasmic_default__span__6FNNC"
                  }
                  style={{
                    fontWeight: 700,
                    color: "var(--token-qvPVZoXe_tpJ)"
                  }}
                >
                  {"Admin Portal"}
                </span>
                <React.Fragment>
                  {
                    ", Executive EcoMunist! Here, you can manually manipulate the database, manage data, test APIs, and view hardware integration docs!"
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
          </Message>
          <Message
            data-plasmic-name={"warningMessage"}
            data-plasmic-override={overrides.warningMessage}
            className={classNames("__wab_instance", sty.warningMessage)}
            closeButton2={
              <XCloseIcon
                className={classNames("all", sty.svg__p4AqU)}
                role={"img"}
              />
            }
            slot={
              <div className={classNames("all", "__wab_text", sty.text__on2Oj)}>
                <React.Fragment>
                  <span
                    className={
                      "plasmic_default__all plasmic_default__span plasmic_default__span__6FNNC"
                    }
                    style={{ fontWeight: 700 }}
                  >
                    {"Warning!"}
                  </span>
                </React.Fragment>
              </div>
            }
            warning={true}
          >
            <div className={classNames("all", "__wab_text", sty.text__irM4)}>
              <React.Fragment>
                <span
                  className={
                    "plasmic_default__all plasmic_default__span plasmic_default__span__6FNNC"
                  }
                  style={{ fontWeight: 700 }}
                >
                  {
                    "Silly mistakes yield disastrous consequences. Do not modify anything unless you know "
                  }
                </span>
                <React.Fragment>{""}</React.Fragment>
                <span
                  className={
                    "plasmic_default__all plasmic_default__span plasmic_default__span__6FNNC"
                  }
                  style={{ fontWeight: 700, fontStyle: "italic" }}
                >
                  {"exactly"}
                </span>
                <React.Fragment>{""}</React.Fragment>
                <span
                  className={
                    "plasmic_default__all plasmic_default__span plasmic_default__span__6FNNC"
                  }
                  style={{ fontWeight: 700 }}
                >
                  {" what you are doing!"}
                </span>
              </React.Fragment>
            </div>
          </Message>
          <NavigationBar
            data-plasmic-name={"navigationBar"}
            data-plasmic-override={overrides.navigationBar}
            className={classNames("__wab_instance", sty.navigationBar)}
            tab={"adminPortal"}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  adminPortalPage: [
    "adminPortalPage",
    "header",
    "h1",
    "welcomeMessage",
    "warningMessage",
    "navigationBar"
  ],
  header: ["header", "h1"],
  h1: ["h1"],
  welcomeMessage: ["welcomeMessage"],
  warningMessage: ["warningMessage"],
  navigationBar: ["navigationBar"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  adminPortalPage: "div";
  header: "div";
  h1: "h1";
  welcomeMessage: typeof Message;
  warningMessage: typeof Message;
  navigationBar: typeof NavigationBar;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAdminPortal__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAdminPortal__VariantsArgs;
    args?: PlasmicAdminPortal__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicAdminPortal__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicAdminPortal__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAdminPortal__ArgProps,
          internalVariantPropNames: PlasmicAdminPortal__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAdminPortal__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "adminPortalPage") {
    func.displayName = "PlasmicAdminPortal";
  } else {
    func.displayName = `PlasmicAdminPortal.${nodeName}`;
  }
  return func;
}

export const PlasmicAdminPortal = Object.assign(
  // Top-level PlasmicAdminPortal renders the root element
  makeNodeComponent("adminPortalPage"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    h1: makeNodeComponent("h1"),
    welcomeMessage: makeNodeComponent("welcomeMessage"),
    warningMessage: makeNodeComponent("warningMessage"),
    navigationBar: makeNodeComponent("navigationBar"),

    // Metadata about props expected for PlasmicAdminPortal
    internalVariantProps: PlasmicAdminPortal__VariantProps,
    internalArgProps: PlasmicAdminPortal__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/admin",
      pagePath: "/admin",
      params: {},
      query: {}
    })
  }
);

export default PlasmicAdminPortal;
/* prettier-ignore-end */
