/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: Gcy8DhclJP5U

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NavigationBar from "../../NavigationBar"; // plasmic-import: 9ar3kGz7iBUD/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicEvents.module.css"; // plasmic-import: Gcy8DhclJP5U/css

import RefreshIcon from "./icons/PlasmicIcon__Refresh"; // plasmic-import: 7WPWcRmpVJdi/icon
import PlusIcon from "./icons/PlasmicIcon__Plus"; // plasmic-import: vPBVvVS45CP9/icon
import SettingsIcon from "./icons/PlasmicIcon__Settings"; // plasmic-import: al57NTSJDXc9/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Manage Events",

    openGraph: {
      title: "Manage Events",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    },
    twitter: {
      card: "summary_large_image" as const,
      title: "Manage Events",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    }
  };
}

export type PlasmicEvents__VariantMembers = {};
export type PlasmicEvents__VariantsArgs = {};
type VariantPropType = keyof PlasmicEvents__VariantsArgs;
export const PlasmicEvents__VariantProps = new Array<VariantPropType>();

export type PlasmicEvents__ArgsType = {};
type ArgPropType = keyof PlasmicEvents__ArgsType;
export const PlasmicEvents__ArgProps = new Array<ArgPropType>();

export type PlasmicEvents__OverridesType = {
  eventsPage?: Flex__<"div">;
  header?: Flex__<"div">;
  headerLabels?: Flex__<"div">;
  h1?: Flex__<"h1">;
  headerButtons?: Flex__<"div">;
  refreshButton?: Flex__<"button">;
  createEventButton?: Flex__<"button">;
  navigationBar?: Flex__<typeof NavigationBar>;
  eventListContainer?: Flex__<"div">;
  massToggleButton?: Flex__<"button">;
};

export interface DefaultEventsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicEvents__RenderFunc(props: {
  variants: PlasmicEvents__VariantsArgs;
  args: PlasmicEvents__ArgsType;
  overrides: PlasmicEvents__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "eventListCollapsed",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => true
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"eventsPage"}
          data-plasmic-override={overrides.eventsPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.eventsPage
          )}
        >
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("all", sty.header)}
          >
            <div
              data-plasmic-name={"headerLabels"}
              data-plasmic-override={overrides.headerLabels}
              className={classNames("all", sty.headerLabels)}
            >
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  "all",
                  "h1",
                  "h1__6FNNC",
                  "__wab_text",
                  sty.h1
                )}
              >
                {"Cleanup Events"}
              </h1>
              <div className={classNames("all", "__wab_text", sty.text__jj6K)}>
                {"View past EcoMunity cleanup events\r\n\r"}
              </div>
            </div>
            <div
              data-plasmic-name={"headerButtons"}
              data-plasmic-override={overrides.headerButtons}
              className={classNames("all", sty.headerButtons)}
            >
              <button
                data-plasmic-name={"refreshButton"}
                data-plasmic-override={overrides.refreshButton}
                className={classNames(
                  "all",
                  "button",
                  "button__6FNNC",
                  sty.refreshButton
                )}
                ref={ref => {
                  $refs["refreshButton"] = ref;
                }}
              >
                <RefreshIcon
                  className={classNames("all", sty.svg__kGj0)}
                  role={"img"}
                />

                <div
                  className={classNames("all", "__wab_text", sty.text__j4DYt)}
                >
                  {"Refresh"}
                </div>
              </button>
              <button
                data-plasmic-name={"createEventButton"}
                data-plasmic-override={overrides.createEventButton}
                className={classNames(
                  "all",
                  "button",
                  "button__6FNNC",
                  sty.createEventButton
                )}
                ref={ref => {
                  $refs["createEventButton"] = ref;
                }}
              >
                <PlusIcon
                  className={classNames("all", sty.svg__bngLh)}
                  role={"img"}
                />

                <div
                  className={classNames("all", "__wab_text", sty.text__e68Er)}
                >
                  {"Create New Event"}
                </div>
              </button>
            </div>
          </div>
          <NavigationBar
            data-plasmic-name={"navigationBar"}
            data-plasmic-override={overrides.navigationBar}
            className={classNames("__wab_instance", sty.navigationBar)}
            tab={"events"}
          />

          <div
            data-plasmic-name={"eventListContainer"}
            data-plasmic-override={overrides.eventListContainer}
            className={classNames("all", sty.eventListContainer)}
          >
            <button
              data-plasmic-name={"massToggleButton"}
              data-plasmic-override={overrides.massToggleButton}
              className={classNames(
                "all",
                "button",
                "button__6FNNC",
                sty.massToggleButton
              )}
              onClick={async event => {
                const $steps = {};

                $steps["updateEventListCollapsed"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["eventListCollapsed"]
                        },
                        operation: 4
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        const oldValue = $stateGet(objRoot, variablePath);
                        $stateSet(objRoot, variablePath, !oldValue);
                        return !oldValue;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateEventListCollapsed"] != null &&
                  typeof $steps["updateEventListCollapsed"] === "object" &&
                  typeof $steps["updateEventListCollapsed"].then === "function"
                ) {
                  $steps["updateEventListCollapsed"] =
                    await $steps["updateEventListCollapsed"];
                }
              }}
              ref={ref => {
                $refs["massToggleButton"] = ref;
              }}
            >
              <SettingsIcon
                className={classNames("all", sty.svg__pzz8P)}
                role={"img"}
              />

              <div className={classNames("all", "__wab_text", sty.text__kris)}>
                <React.Fragment>
                  {(() => {
                    try {
                      return $state.eventListCollapsed
                        ? "Expand All"
                        : "Collapse All";
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "Expand / Collapse All";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
            </button>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  eventsPage: [
    "eventsPage",
    "header",
    "headerLabels",
    "h1",
    "headerButtons",
    "refreshButton",
    "createEventButton",
    "navigationBar",
    "eventListContainer",
    "massToggleButton"
  ],
  header: [
    "header",
    "headerLabels",
    "h1",
    "headerButtons",
    "refreshButton",
    "createEventButton"
  ],
  headerLabels: ["headerLabels", "h1"],
  h1: ["h1"],
  headerButtons: ["headerButtons", "refreshButton", "createEventButton"],
  refreshButton: ["refreshButton"],
  createEventButton: ["createEventButton"],
  navigationBar: ["navigationBar"],
  eventListContainer: ["eventListContainer", "massToggleButton"],
  massToggleButton: ["massToggleButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  eventsPage: "div";
  header: "div";
  headerLabels: "div";
  h1: "h1";
  headerButtons: "div";
  refreshButton: "button";
  createEventButton: "button";
  navigationBar: typeof NavigationBar;
  eventListContainer: "div";
  massToggleButton: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicEvents__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicEvents__VariantsArgs;
    args?: PlasmicEvents__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicEvents__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicEvents__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicEvents__ArgProps,
          internalVariantPropNames: PlasmicEvents__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicEvents__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "eventsPage") {
    func.displayName = "PlasmicEvents";
  } else {
    func.displayName = `PlasmicEvents.${nodeName}`;
  }
  return func;
}

export const PlasmicEvents = Object.assign(
  // Top-level PlasmicEvents renders the root element
  makeNodeComponent("eventsPage"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    headerLabels: makeNodeComponent("headerLabels"),
    h1: makeNodeComponent("h1"),
    headerButtons: makeNodeComponent("headerButtons"),
    refreshButton: makeNodeComponent("refreshButton"),
    createEventButton: makeNodeComponent("createEventButton"),
    navigationBar: makeNodeComponent("navigationBar"),
    eventListContainer: makeNodeComponent("eventListContainer"),
    massToggleButton: makeNodeComponent("massToggleButton"),

    // Metadata about props expected for PlasmicEvents
    internalVariantProps: PlasmicEvents__VariantProps,
    internalArgProps: PlasmicEvents__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/events",
      pagePath: "/events",
      params: {},
      query: {}
    })
  }
);

export default PlasmicEvents;
/* prettier-ignore-end */
