/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: 3i9Xvqt5CyxM

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TextField from "../../TextField"; // plasmic-import: nhNi86WWHkJQ/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicChangePassword.module.css"; // plasmic-import: 3i9Xvqt5CyxM/css

import LockIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__Lock"; // plasmic-import: hwRGGXIppyrw/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 0qv-KGqIe6NJ/icon
import LockCheckIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__LockCheck"; // plasmic-import: SGlCUZH698Md/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Change Password",

    openGraph: {
      title: "Change Password",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    },
    twitter: {
      card: "summary_large_image" as const,
      title: "Change Password",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    }
  };
}

export type PlasmicChangePassword__VariantMembers = {};
export type PlasmicChangePassword__VariantsArgs = {};
type VariantPropType = keyof PlasmicChangePassword__VariantsArgs;
export const PlasmicChangePassword__VariantProps = new Array<VariantPropType>();

export type PlasmicChangePassword__ArgsType = {};
type ArgPropType = keyof PlasmicChangePassword__ArgsType;
export const PlasmicChangePassword__ArgProps = new Array<ArgPropType>();

export type PlasmicChangePassword__OverridesType = {
  changePasswordPage?: Flex__<"div">;
  flex?: Flex__<"div">;
  changePasswordContainer?: Flex__<"div">;
  currentPasswordContainer?: Flex__<typeof TextField>;
  newPasswordContainer?: Flex__<typeof TextField>;
  confirmNewPasswordContainer?: Flex__<typeof TextField>;
  passwordError?: Flex__<"div">;
  passwordErrorContent?: Flex__<"div">;
  continueButton?: Flex__<"button">;
  backButton?: Flex__<"button">;
  resetPasswordContainer?: Flex__<"div">;
  resetNewPasswordContainer?: Flex__<typeof TextField>;
  resetConfirmNewPasswordContainer?: Flex__<typeof TextField>;
  resetPasswordError?: Flex__<"div">;
  passwordErrorContent2?: Flex__<"div">;
  resetContinueButton?: Flex__<"button">;
  successContainer?: Flex__<"div">;
  notice?: Flex__<"h1">;
  toDashboardButton?: Flex__<"button">;
  resetSuccessContainer?: Flex__<"div">;
  resetNotice?: Flex__<"h1">;
  toLogInButton?: Flex__<"button">;
};

export interface DefaultChangePasswordProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicChangePassword__RenderFunc(props: {
  variants: PlasmicChangePassword__VariantsArgs;
  args: PlasmicChangePassword__ArgsType;
  overrides: PlasmicChangePassword__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "currentPasswordContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "newPasswordContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "confirmNewPasswordContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "resetNewPasswordContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "resetConfirmNewPasswordContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"changePasswordPage"}
        data-plasmic-override={overrides.changePasswordPage}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          "all",
          "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
          "plasmic_default_styles",
          "plasmic_mixins",
          styleTokensClassNames,
          sty.changePasswordPage
        )}
      >
        <div
          data-plasmic-name={"flex"}
          data-plasmic-override={overrides.flex}
          className={classNames("all", sty.flex)}
        >
          <div
            data-plasmic-name={"changePasswordContainer"}
            data-plasmic-override={overrides.changePasswordContainer}
            className={classNames("all", sty.changePasswordContainer)}
          >
            <h1
              className={classNames(
                "all",
                "h1",
                "h1__6FNNC",
                "__wab_text",
                sty.h1__qjIwb
              )}
            >
              {"Change Password"}
            </h1>
            <TextField
              data-plasmic-name={"currentPasswordContainer"}
              data-plasmic-override={overrides.currentPasswordContainer}
              autoComplete={["off"]}
              className={classNames(
                "__wab_instance",
                sty.currentPasswordContainer
              )}
              description={""}
              disabled={false}
              iconStart={true}
              inputMode={"text"}
              label={
                <div
                  className={classNames("all", "__wab_text", sty.text__c9Bwt)}
                >
                  {"Current Password"}
                </div>
              }
              onChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "currentPasswordContainer",
                  "value"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"..."}
              showDescription={false}
              showLabel={true}
              start={
                <LockIcon
                  className={classNames("all", sty.svg__ockgt)}
                  role={"img"}
                />
              }
              type={"password"}
              value={generateStateValueProp($state, [
                "currentPasswordContainer",
                "value"
              ])}
            />

            <TextField
              data-plasmic-name={"newPasswordContainer"}
              data-plasmic-override={overrides.newPasswordContainer}
              autoComplete={["off"]}
              className={classNames("__wab_instance", sty.newPasswordContainer)}
              description={""}
              disabled={false}
              iconStart={true}
              inputMode={"text"}
              label={
                <div
                  className={classNames("all", "__wab_text", sty.text__hZvb6)}
                >
                  {"New Password"}
                </div>
              }
              onChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "newPasswordContainer",
                  "value"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"..."}
              showDescription={false}
              showLabel={true}
              start={
                <LockIcon
                  className={classNames("all", sty.svg___1Vzx9)}
                  role={"img"}
                />
              }
              type={"password"}
              value={generateStateValueProp($state, [
                "newPasswordContainer",
                "value"
              ])}
            />

            <TextField
              data-plasmic-name={"confirmNewPasswordContainer"}
              data-plasmic-override={overrides.confirmNewPasswordContainer}
              autoComplete={["off"]}
              className={classNames(
                "__wab_instance",
                sty.confirmNewPasswordContainer
              )}
              description={""}
              disabled={false}
              iconStart={true}
              inputMode={"text"}
              label={
                <div
                  className={classNames("all", "__wab_text", sty.text__slNce)}
                >
                  {"Confirm New Password"}
                </div>
              }
              onChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "confirmNewPasswordContainer",
                  "value"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"..."}
              showDescription={false}
              showLabel={true}
              start={
                <LockCheckIcon
                  className={classNames("all", sty.svg__u19Bx)}
                  role={"img"}
                />
              }
              type={"password"}
              value={generateStateValueProp($state, [
                "confirmNewPasswordContainer",
                "value"
              ])}
            />

            <div
              data-plasmic-name={"passwordError"}
              data-plasmic-override={overrides.passwordError}
              className={classNames("all", sty.passwordError)}
            >
              <div
                data-plasmic-name={"passwordErrorContent"}
                data-plasmic-override={overrides.passwordErrorContent}
                className={classNames(
                  "all",
                  "__wab_text",
                  sty.passwordErrorContent
                )}
              >
                {"Password must be..."}
              </div>
            </div>
            <button
              data-plasmic-name={"continueButton"}
              data-plasmic-override={overrides.continueButton}
              className={classNames(
                "all",
                "button",
                "button__6FNNC",
                sty.continueButton
              )}
              ref={ref => {
                $refs["continueButton"] = ref;
              }}
            >
              <div className={classNames("all", "__wab_text", sty.text___7RZa)}>
                {"Continue"}
              </div>
            </button>
            <button
              data-plasmic-name={"backButton"}
              data-plasmic-override={overrides.backButton}
              className={classNames(
                "all",
                "button",
                "button__6FNNC",
                sty.backButton
              )}
              onClick={async event => {
                const $steps = {};

                $steps["goToProfile"] = true
                  ? (() => {
                      const actionArgs = { destination: `/profile` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToProfile"] != null &&
                  typeof $steps["goToProfile"] === "object" &&
                  typeof $steps["goToProfile"].then === "function"
                ) {
                  $steps["goToProfile"] = await $steps["goToProfile"];
                }
              }}
              ref={ref => {
                $refs["backButton"] = ref;
              }}
            >
              <div className={classNames("all", "__wab_text", sty.text__fjhvR)}>
                {"Go Back"}
              </div>
            </button>
          </div>
          <div
            data-plasmic-name={"resetPasswordContainer"}
            data-plasmic-override={overrides.resetPasswordContainer}
            className={classNames("all", sty.resetPasswordContainer)}
          >
            <h1
              className={classNames(
                "all",
                "h1",
                "h1__6FNNC",
                "__wab_text",
                sty.h1__wHz65
              )}
            >
              {"Reset Password"}
            </h1>
            <TextField
              data-plasmic-name={"resetNewPasswordContainer"}
              data-plasmic-override={overrides.resetNewPasswordContainer}
              autoComplete={["off"]}
              className={classNames(
                "__wab_instance",
                sty.resetNewPasswordContainer
              )}
              description={""}
              disabled={false}
              iconStart={true}
              inputMode={"text"}
              label={
                <div
                  className={classNames("all", "__wab_text", sty.text__buu1K)}
                >
                  {"New Password"}
                </div>
              }
              onChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "resetNewPasswordContainer",
                  "value"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"..."}
              showDescription={false}
              showLabel={true}
              start={
                <LockIcon
                  className={classNames("all", sty.svg__rJpqS)}
                  role={"img"}
                />
              }
              type={"password"}
              value={generateStateValueProp($state, [
                "resetNewPasswordContainer",
                "value"
              ])}
            />

            <TextField
              data-plasmic-name={"resetConfirmNewPasswordContainer"}
              data-plasmic-override={overrides.resetConfirmNewPasswordContainer}
              autoComplete={["off"]}
              className={classNames(
                "__wab_instance",
                sty.resetConfirmNewPasswordContainer
              )}
              description={""}
              disabled={false}
              iconStart={true}
              inputMode={"text"}
              label={
                <div
                  className={classNames("all", "__wab_text", sty.text__bgYxG)}
                >
                  {"Confirm New Password"}
                </div>
              }
              onChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "resetConfirmNewPasswordContainer",
                  "value"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"..."}
              showDescription={false}
              showLabel={true}
              start={
                <LockCheckIcon
                  className={classNames("all", sty.svg__cr2Y6)}
                  role={"img"}
                />
              }
              type={"password"}
              value={generateStateValueProp($state, [
                "resetConfirmNewPasswordContainer",
                "value"
              ])}
            />

            <div
              data-plasmic-name={"resetPasswordError"}
              data-plasmic-override={overrides.resetPasswordError}
              className={classNames("all", sty.resetPasswordError)}
            >
              <div
                data-plasmic-name={"passwordErrorContent2"}
                data-plasmic-override={overrides.passwordErrorContent2}
                className={classNames(
                  "all",
                  "__wab_text",
                  sty.passwordErrorContent2
                )}
              >
                {"Password must be..."}
              </div>
            </div>
            <button
              data-plasmic-name={"resetContinueButton"}
              data-plasmic-override={overrides.resetContinueButton}
              className={classNames(
                "all",
                "button",
                "button__6FNNC",
                sty.resetContinueButton
              )}
              ref={ref => {
                $refs["resetContinueButton"] = ref;
              }}
            >
              <div className={classNames("all", "__wab_text", sty.text__xpMdu)}>
                {"Continue"}
              </div>
            </button>
          </div>
          <div
            data-plasmic-name={"successContainer"}
            data-plasmic-override={overrides.successContainer}
            className={classNames("all", sty.successContainer)}
          >
            <h1
              data-plasmic-name={"notice"}
              data-plasmic-override={overrides.notice}
              className={classNames(
                "all",
                "h1",
                "h1__6FNNC",
                "__wab_text",
                sty.notice
              )}
            >
              <React.Fragment>
                <span
                  className={
                    "plasmic_default__all plasmic_default__span plasmic_default__span__6FNNC"
                  }
                  style={{ color: "var(--token-ytzaa9i3sK9d)" }}
                >
                  {"Success!"}
                </span>
                <React.Fragment>
                  {"\n\nYour password has been changed."}
                </React.Fragment>
              </React.Fragment>
            </h1>
            <button
              data-plasmic-name={"toDashboardButton"}
              data-plasmic-override={overrides.toDashboardButton}
              className={classNames(
                "all",
                "button",
                "button__6FNNC",
                sty.toDashboardButton
              )}
              onClick={async event => {
                const $steps = {};

                $steps["goToDashboard"] = true
                  ? (() => {
                      const actionArgs = { destination: `/dashboard` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToDashboard"] != null &&
                  typeof $steps["goToDashboard"] === "object" &&
                  typeof $steps["goToDashboard"].then === "function"
                ) {
                  $steps["goToDashboard"] = await $steps["goToDashboard"];
                }
              }}
              ref={ref => {
                $refs["toDashboardButton"] = ref;
              }}
            >
              <div className={classNames("all", "__wab_text", sty.text__e4Tm)}>
                {"Go To Dashboard"}
              </div>
            </button>
          </div>
          <div
            data-plasmic-name={"resetSuccessContainer"}
            data-plasmic-override={overrides.resetSuccessContainer}
            className={classNames("all", sty.resetSuccessContainer)}
          >
            <h1
              data-plasmic-name={"resetNotice"}
              data-plasmic-override={overrides.resetNotice}
              className={classNames(
                "all",
                "h1",
                "h1__6FNNC",
                "__wab_text",
                sty.resetNotice
              )}
            >
              <React.Fragment>
                <span
                  className={
                    "plasmic_default__all plasmic_default__span plasmic_default__span__6FNNC"
                  }
                  style={{ color: "var(--token-ytzaa9i3sK9d)" }}
                >
                  {"Success!"}
                </span>
                <React.Fragment>
                  {"\n\nYour password has been reset."}
                </React.Fragment>
              </React.Fragment>
            </h1>
            <button
              data-plasmic-name={"toLogInButton"}
              data-plasmic-override={overrides.toLogInButton}
              className={classNames(
                "all",
                "button",
                "button__6FNNC",
                sty.toLogInButton
              )}
              onClick={async event => {
                const $steps = {};

                $steps["goToLogIn"] = true
                  ? (() => {
                      const actionArgs = { destination: `/log-in` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToLogIn"] != null &&
                  typeof $steps["goToLogIn"] === "object" &&
                  typeof $steps["goToLogIn"].then === "function"
                ) {
                  $steps["goToLogIn"] = await $steps["goToLogIn"];
                }
              }}
              ref={ref => {
                $refs["toLogInButton"] = ref;
              }}
            >
              <div
                className={classNames("all", "__wab_text", sty.text___6Y0EE)}
              >
                {"Log In"}
              </div>
            </button>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  changePasswordPage: [
    "changePasswordPage",
    "flex",
    "changePasswordContainer",
    "currentPasswordContainer",
    "newPasswordContainer",
    "confirmNewPasswordContainer",
    "passwordError",
    "passwordErrorContent",
    "continueButton",
    "backButton",
    "resetPasswordContainer",
    "resetNewPasswordContainer",
    "resetConfirmNewPasswordContainer",
    "resetPasswordError",
    "passwordErrorContent2",
    "resetContinueButton",
    "successContainer",
    "notice",
    "toDashboardButton",
    "resetSuccessContainer",
    "resetNotice",
    "toLogInButton"
  ],
  flex: [
    "flex",
    "changePasswordContainer",
    "currentPasswordContainer",
    "newPasswordContainer",
    "confirmNewPasswordContainer",
    "passwordError",
    "passwordErrorContent",
    "continueButton",
    "backButton",
    "resetPasswordContainer",
    "resetNewPasswordContainer",
    "resetConfirmNewPasswordContainer",
    "resetPasswordError",
    "passwordErrorContent2",
    "resetContinueButton",
    "successContainer",
    "notice",
    "toDashboardButton",
    "resetSuccessContainer",
    "resetNotice",
    "toLogInButton"
  ],
  changePasswordContainer: [
    "changePasswordContainer",
    "currentPasswordContainer",
    "newPasswordContainer",
    "confirmNewPasswordContainer",
    "passwordError",
    "passwordErrorContent",
    "continueButton",
    "backButton"
  ],
  currentPasswordContainer: ["currentPasswordContainer"],
  newPasswordContainer: ["newPasswordContainer"],
  confirmNewPasswordContainer: ["confirmNewPasswordContainer"],
  passwordError: ["passwordError", "passwordErrorContent"],
  passwordErrorContent: ["passwordErrorContent"],
  continueButton: ["continueButton"],
  backButton: ["backButton"],
  resetPasswordContainer: [
    "resetPasswordContainer",
    "resetNewPasswordContainer",
    "resetConfirmNewPasswordContainer",
    "resetPasswordError",
    "passwordErrorContent2",
    "resetContinueButton"
  ],
  resetNewPasswordContainer: ["resetNewPasswordContainer"],
  resetConfirmNewPasswordContainer: ["resetConfirmNewPasswordContainer"],
  resetPasswordError: ["resetPasswordError", "passwordErrorContent2"],
  passwordErrorContent2: ["passwordErrorContent2"],
  resetContinueButton: ["resetContinueButton"],
  successContainer: ["successContainer", "notice", "toDashboardButton"],
  notice: ["notice"],
  toDashboardButton: ["toDashboardButton"],
  resetSuccessContainer: [
    "resetSuccessContainer",
    "resetNotice",
    "toLogInButton"
  ],
  resetNotice: ["resetNotice"],
  toLogInButton: ["toLogInButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  changePasswordPage: "div";
  flex: "div";
  changePasswordContainer: "div";
  currentPasswordContainer: typeof TextField;
  newPasswordContainer: typeof TextField;
  confirmNewPasswordContainer: typeof TextField;
  passwordError: "div";
  passwordErrorContent: "div";
  continueButton: "button";
  backButton: "button";
  resetPasswordContainer: "div";
  resetNewPasswordContainer: typeof TextField;
  resetConfirmNewPasswordContainer: typeof TextField;
  resetPasswordError: "div";
  passwordErrorContent2: "div";
  resetContinueButton: "button";
  successContainer: "div";
  notice: "h1";
  toDashboardButton: "button";
  resetSuccessContainer: "div";
  resetNotice: "h1";
  toLogInButton: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicChangePassword__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicChangePassword__VariantsArgs;
    args?: PlasmicChangePassword__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicChangePassword__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicChangePassword__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicChangePassword__ArgProps,
          internalVariantPropNames: PlasmicChangePassword__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicChangePassword__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "changePasswordPage") {
    func.displayName = "PlasmicChangePassword";
  } else {
    func.displayName = `PlasmicChangePassword.${nodeName}`;
  }
  return func;
}

export const PlasmicChangePassword = Object.assign(
  // Top-level PlasmicChangePassword renders the root element
  makeNodeComponent("changePasswordPage"),
  {
    // Helper components rendering sub-elements
    flex: makeNodeComponent("flex"),
    changePasswordContainer: makeNodeComponent("changePasswordContainer"),
    currentPasswordContainer: makeNodeComponent("currentPasswordContainer"),
    newPasswordContainer: makeNodeComponent("newPasswordContainer"),
    confirmNewPasswordContainer: makeNodeComponent(
      "confirmNewPasswordContainer"
    ),
    passwordError: makeNodeComponent("passwordError"),
    passwordErrorContent: makeNodeComponent("passwordErrorContent"),
    continueButton: makeNodeComponent("continueButton"),
    backButton: makeNodeComponent("backButton"),
    resetPasswordContainer: makeNodeComponent("resetPasswordContainer"),
    resetNewPasswordContainer: makeNodeComponent("resetNewPasswordContainer"),
    resetConfirmNewPasswordContainer: makeNodeComponent(
      "resetConfirmNewPasswordContainer"
    ),
    resetPasswordError: makeNodeComponent("resetPasswordError"),
    passwordErrorContent2: makeNodeComponent("passwordErrorContent2"),
    resetContinueButton: makeNodeComponent("resetContinueButton"),
    successContainer: makeNodeComponent("successContainer"),
    notice: makeNodeComponent("notice"),
    toDashboardButton: makeNodeComponent("toDashboardButton"),
    resetSuccessContainer: makeNodeComponent("resetSuccessContainer"),
    resetNotice: makeNodeComponent("resetNotice"),
    toLogInButton: makeNodeComponent("toLogInButton"),

    // Metadata about props expected for PlasmicChangePassword
    internalVariantProps: PlasmicChangePassword__VariantProps,
    internalArgProps: PlasmicChangePassword__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/change-password",
      pagePath: "/change-password",
      params: {},
      query: {}
    })
  }
);

export default PlasmicChangePassword;
/* prettier-ignore-end */
