/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: 9ar3kGz7iBUD

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicNavigationBar.module.css"; // plasmic-import: 9ar3kGz7iBUD/css

import LayoutDashboardIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__LayoutDashboard"; // plasmic-import: HWTpSbFCoWAh/icon
import LayoutDashboardFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__LayoutDashboardFilled"; // plasmic-import: _xQ2qZ4iPYcE/icon
import CalendarIcon from "./icons/PlasmicIcon__Calendar"; // plasmic-import: CPTBTnszI8ug/icon
import UserIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__User"; // plasmic-import: d1LJS78vGoJH/icon
import UserFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__UserFilled"; // plasmic-import: 2Yu5Q5j4morB/icon
import SettingsCogIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__SettingsCog"; // plasmic-import: 9qK83KbdR3Yy/icon
import SettingsFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__SettingsFilled"; // plasmic-import: RiaJeooMb1Et/icon

export type PlasmicNavigationBar__VariantMembers = {
  tab: "dashboard" | "events" | "adminPortal" | "profile";
};
export type PlasmicNavigationBar__VariantsArgs = {
  tab?: SingleChoiceArg<"dashboard" | "events" | "adminPortal" | "profile">;
};
type VariantPropType = keyof PlasmicNavigationBar__VariantsArgs;
export const PlasmicNavigationBar__VariantProps = new Array<VariantPropType>(
  "tab"
);

export type PlasmicNavigationBar__ArgsType = {};
type ArgPropType = keyof PlasmicNavigationBar__ArgsType;
export const PlasmicNavigationBar__ArgProps = new Array<ArgPropType>();

export type PlasmicNavigationBar__OverridesType = {
  navigationBar?: Flex__<"div">;
  dashboardPageButton?: Flex__<"button">;
  sessionsPageButton?: Flex__<"button">;
  profilePageButton?: Flex__<"button">;
  text?: Flex__<"div">;
  adminPortalButton?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultNavigationBarProps {
  tab?: SingleChoiceArg<"dashboard" | "events" | "adminPortal" | "profile">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavigationBar__RenderFunc(props: {
  variants: PlasmicNavigationBar__VariantsArgs;
  args: PlasmicNavigationBar__ArgsType;
  overrides: PlasmicNavigationBar__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "tab",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.tab
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"navigationBar"}
      data-plasmic-override={overrides.navigationBar}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.navigationBar,
        {
          [sty.navigationBartab_adminPortal]: hasVariant(
            $state,
            "tab",
            "adminPortal"
          )
        }
      )}
    >
      <button
        data-plasmic-name={"dashboardPageButton"}
        data-plasmic-override={overrides.dashboardPageButton}
        className={classNames(
          "all",
          "button",
          "button__6FNNC",
          sty.dashboardPageButton,
          {
            [sty.dashboardPageButtontab_adminPortal]: hasVariant(
              $state,
              "tab",
              "adminPortal"
            ),
            [sty.dashboardPageButtontab_dashboard]: hasVariant(
              $state,
              "tab",
              "dashboard"
            ),
            [sty.dashboardPageButtontab_events]: hasVariant(
              $state,
              "tab",
              "events"
            )
          }
        )}
        onClick={async event => {
          const $steps = {};

          $steps["goToDashboard"] = true
            ? (() => {
                const actionArgs = { destination: `/dashboard` };
                return (({ destination }) => {
                  if (
                    typeof destination === "string" &&
                    destination.startsWith("#")
                  ) {
                    document
                      .getElementById(destination.substr(1))
                      .scrollIntoView({ behavior: "smooth" });
                  } else {
                    __nextRouter?.push(destination);
                  }
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["goToDashboard"] != null &&
            typeof $steps["goToDashboard"] === "object" &&
            typeof $steps["goToDashboard"].then === "function"
          ) {
            $steps["goToDashboard"] = await $steps["goToDashboard"];
          }
        }}
        ref={ref => {
          $refs["dashboardPageButton"] = ref;
        }}
      >
        <PlasmicIcon__
          PlasmicIconType={
            hasVariant($state, "tab", "dashboard")
              ? LayoutDashboardFilledIcon
              : LayoutDashboardIcon
          }
          className={classNames("all", sty.svg__anMfb, {
            [sty.svgtab_dashboard__anMfblOhXr]: hasVariant(
              $state,
              "tab",
              "dashboard"
            )
          })}
          role={"img"}
        />

        <h1
          className={classNames(
            "all",
            "h1",
            "h1__6FNNC",
            "__wab_text",
            sty.h1__hlXHk,
            {
              [sty.h1tab_adminPortal__hlXHkqxQ]: hasVariant(
                $state,
                "tab",
                "adminPortal"
              )
            }
          )}
        >
          {"Dashboard"}
        </h1>
      </button>
      <button
        data-plasmic-name={"sessionsPageButton"}
        data-plasmic-override={overrides.sessionsPageButton}
        className={classNames(
          "all",
          "button",
          "button__6FNNC",
          sty.sessionsPageButton,
          {
            [sty.sessionsPageButtontab_adminPortal]: hasVariant(
              $state,
              "tab",
              "adminPortal"
            ),
            [sty.sessionsPageButtontab_dashboard]: hasVariant(
              $state,
              "tab",
              "dashboard"
            ),
            [sty.sessionsPageButtontab_events]: hasVariant(
              $state,
              "tab",
              "events"
            )
          }
        )}
        onClick={async event => {
          const $steps = {};

          $steps["goToSessions"] = true
            ? (() => {
                const actionArgs = { destination: `/events` };
                return (({ destination }) => {
                  if (
                    typeof destination === "string" &&
                    destination.startsWith("#")
                  ) {
                    document
                      .getElementById(destination.substr(1))
                      .scrollIntoView({ behavior: "smooth" });
                  } else {
                    __nextRouter?.push(destination);
                  }
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["goToSessions"] != null &&
            typeof $steps["goToSessions"] === "object" &&
            typeof $steps["goToSessions"].then === "function"
          ) {
            $steps["goToSessions"] = await $steps["goToSessions"];
          }
        }}
        ref={ref => {
          $refs["sessionsPageButton"] = ref;
        }}
      >
        <CalendarIcon
          className={classNames("all", sty.svg___0YQGt, {
            [sty.svgtab_adminPortal___0YQGtqxQ]: hasVariant(
              $state,
              "tab",
              "adminPortal"
            ),
            [sty.svgtab_dashboard___0YQGtlOhXr]: hasVariant(
              $state,
              "tab",
              "dashboard"
            ),
            [sty.svgtab_events___0YQGtCjXp]: hasVariant($state, "tab", "events")
          })}
          role={"img"}
        />

        <h1
          className={classNames(
            "all",
            "h1",
            "h1__6FNNC",
            "__wab_text",
            sty.h1__rhWh8
          )}
        >
          {"Events"}
        </h1>
      </button>
      <button
        data-plasmic-name={"profilePageButton"}
        data-plasmic-override={overrides.profilePageButton}
        className={classNames(
          "all",
          "button",
          "button__6FNNC",
          sty.profilePageButton,
          {
            [sty.profilePageButtontab_adminPortal]: hasVariant(
              $state,
              "tab",
              "adminPortal"
            ),
            [sty.profilePageButtontab_dashboard]: hasVariant(
              $state,
              "tab",
              "dashboard"
            ),
            [sty.profilePageButtontab_events]: hasVariant(
              $state,
              "tab",
              "events"
            ),
            [sty.profilePageButtontab_profile]: hasVariant(
              $state,
              "tab",
              "profile"
            )
          }
        )}
        onClick={async event => {
          const $steps = {};

          $steps["goToProfile"] = true
            ? (() => {
                const actionArgs = { destination: `/profile` };
                return (({ destination }) => {
                  if (
                    typeof destination === "string" &&
                    destination.startsWith("#")
                  ) {
                    document
                      .getElementById(destination.substr(1))
                      .scrollIntoView({ behavior: "smooth" });
                  } else {
                    __nextRouter?.push(destination);
                  }
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["goToProfile"] != null &&
            typeof $steps["goToProfile"] === "object" &&
            typeof $steps["goToProfile"].then === "function"
          ) {
            $steps["goToProfile"] = await $steps["goToProfile"];
          }
        }}
        ref={ref => {
          $refs["profilePageButton"] = ref;
        }}
      >
        <PlasmicIcon__
          PlasmicIconType={
            hasVariant($state, "tab", "profile") ? UserFilledIcon : UserIcon
          }
          className={classNames("all", sty.svg__zp5VL, {
            [sty.svgtab_adminPortal__zp5VLqxQ]: hasVariant(
              $state,
              "tab",
              "adminPortal"
            ),
            [sty.svgtab_dashboard__zp5VLlOhXr]: hasVariant(
              $state,
              "tab",
              "dashboard"
            ),
            [sty.svgtab_profile__zp5VL749HV]: hasVariant(
              $state,
              "tab",
              "profile"
            )
          })}
          role={"img"}
        />

        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames("all", "__wab_text", sty.text)}
        >
          {"Log Out"}
        </div>
        <h1
          className={classNames(
            "all",
            "h1",
            "h1__6FNNC",
            "__wab_text",
            sty.h1__pwh3
          )}
        >
          {"Profile"}
        </h1>
      </button>
      <PlasmicLink__
        data-plasmic-name={"adminPortalButton"}
        data-plasmic-override={overrides.adminPortalButton}
        className={classNames("all", "a", "a__6FNNC", sty.adminPortalButton, {
          [sty.adminPortalButtontab_adminPortal]: hasVariant(
            $state,
            "tab",
            "adminPortal"
          ),
          [sty.adminPortalButtontab_dashboard]: hasVariant(
            $state,
            "tab",
            "dashboard"
          ),
          [sty.adminPortalButtontab_events]: hasVariant(
            $state,
            "tab",
            "events"
          ),
          [sty.adminPortalButtontab_profile]: hasVariant(
            $state,
            "tab",
            "profile"
          )
        })}
        component={Link}
        href={`/admin`}
        legacyBehavior={false}
        platform={"nextjs"}
        target={hasVariant($state, "tab", "dashboard") ? undefined : undefined}
      >
        <PlasmicIcon__
          PlasmicIconType={
            hasVariant($state, "tab", "adminPortal")
              ? SettingsFilledIcon
              : SettingsCogIcon
          }
          className={classNames("all", sty.svg__rm7Zi, {
            [sty.svgtab_adminPortal__rm7ZiqxQ]: hasVariant(
              $state,
              "tab",
              "adminPortal"
            ),
            [sty.svgtab_dashboard__rm7ZilOhXr]: hasVariant(
              $state,
              "tab",
              "dashboard"
            )
          })}
          role={"img"}
        />

        <h1
          className={classNames(
            "all",
            "h1",
            "h1__6FNNC",
            "__wab_text",
            sty.h1__rmN0I
          )}
        >
          {"Admin"}
        </h1>
      </PlasmicLink__>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  navigationBar: [
    "navigationBar",
    "dashboardPageButton",
    "sessionsPageButton",
    "profilePageButton",
    "text",
    "adminPortalButton"
  ],
  dashboardPageButton: ["dashboardPageButton"],
  sessionsPageButton: ["sessionsPageButton"],
  profilePageButton: ["profilePageButton", "text"],
  text: ["text"],
  adminPortalButton: ["adminPortalButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  navigationBar: "div";
  dashboardPageButton: "button";
  sessionsPageButton: "button";
  profilePageButton: "button";
  text: "div";
  adminPortalButton: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavigationBar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavigationBar__VariantsArgs;
    args?: PlasmicNavigationBar__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNavigationBar__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNavigationBar__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavigationBar__ArgProps,
          internalVariantPropNames: PlasmicNavigationBar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavigationBar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "navigationBar") {
    func.displayName = "PlasmicNavigationBar";
  } else {
    func.displayName = `PlasmicNavigationBar.${nodeName}`;
  }
  return func;
}

export const PlasmicNavigationBar = Object.assign(
  // Top-level PlasmicNavigationBar renders the root element
  makeNodeComponent("navigationBar"),
  {
    // Helper components rendering sub-elements
    dashboardPageButton: makeNodeComponent("dashboardPageButton"),
    sessionsPageButton: makeNodeComponent("sessionsPageButton"),
    profilePageButton: makeNodeComponent("profilePageButton"),
    text: makeNodeComponent("text"),
    adminPortalButton: makeNodeComponent("adminPortalButton"),

    // Metadata about props expected for PlasmicNavigationBar
    internalVariantProps: PlasmicNavigationBar__VariantProps,
    internalArgProps: PlasmicNavigationBar__ArgProps
  }
);

export default PlasmicNavigationBar;
/* prettier-ignore-end */
