/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: Y3XcaRKO2nbo

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicLogOut.module.css"; // plasmic-import: Y3XcaRKO2nbo/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Log Out",

    openGraph: {
      title: "Log Out",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    },
    twitter: {
      card: "summary_large_image" as const,
      title: "Log Out",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    }
  };
}

export type PlasmicLogOut__VariantMembers = {};
export type PlasmicLogOut__VariantsArgs = {};
type VariantPropType = keyof PlasmicLogOut__VariantsArgs;
export const PlasmicLogOut__VariantProps = new Array<VariantPropType>();

export type PlasmicLogOut__ArgsType = {};
type ArgPropType = keyof PlasmicLogOut__ArgsType;
export const PlasmicLogOut__ArgProps = new Array<ArgPropType>();

export type PlasmicLogOut__OverridesType = {
  logOutPage?: Flex__<"div">;
  flex?: Flex__<"div">;
  container?: Flex__<"div">;
  notice?: Flex__<"h1">;
  continueButton?: Flex__<"button">;
  backButton?: Flex__<"button">;
};

export interface DefaultLogOutProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLogOut__RenderFunc(props: {
  variants: PlasmicLogOut__VariantsArgs;
  args: PlasmicLogOut__ArgsType;
  overrides: PlasmicLogOut__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"logOutPage"}
          data-plasmic-override={overrides.logOutPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.logOutPage
          )}
        >
          <div
            data-plasmic-name={"flex"}
            data-plasmic-override={overrides.flex}
            className={classNames("all", sty.flex)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames("all", sty.container)}
            >
              <h1
                data-plasmic-name={"notice"}
                data-plasmic-override={overrides.notice}
                className={classNames(
                  "all",
                  "h1",
                  "h1__6FNNC",
                  "__wab_text",
                  sty.notice
                )}
              >
                {"Log out of your account?"}
              </h1>
              <button
                data-plasmic-name={"continueButton"}
                data-plasmic-override={overrides.continueButton}
                className={classNames(
                  "all",
                  "button",
                  "button__6FNNC",
                  sty.continueButton
                )}
                ref={ref => {
                  $refs["continueButton"] = ref;
                }}
              >
                <div
                  className={classNames("all", "__wab_text", sty.text__uKdid)}
                >
                  {"Continue"}
                </div>
              </button>
              <button
                data-plasmic-name={"backButton"}
                data-plasmic-override={overrides.backButton}
                className={classNames(
                  "all",
                  "button",
                  "button__6FNNC",
                  sty.backButton
                )}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToProfile"] = true
                    ? (() => {
                        const actionArgs = { destination: `/profile` };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToProfile"] != null &&
                    typeof $steps["goToProfile"] === "object" &&
                    typeof $steps["goToProfile"].then === "function"
                  ) {
                    $steps["goToProfile"] = await $steps["goToProfile"];
                  }
                }}
                ref={ref => {
                  $refs["backButton"] = ref;
                }}
              >
                <div
                  className={classNames("all", "__wab_text", sty.text__dqETg)}
                >
                  {"Go Back"}
                </div>
              </button>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  logOutPage: [
    "logOutPage",
    "flex",
    "container",
    "notice",
    "continueButton",
    "backButton"
  ],
  flex: ["flex", "container", "notice", "continueButton", "backButton"],
  container: ["container", "notice", "continueButton", "backButton"],
  notice: ["notice"],
  continueButton: ["continueButton"],
  backButton: ["backButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  logOutPage: "div";
  flex: "div";
  container: "div";
  notice: "h1";
  continueButton: "button";
  backButton: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogOut__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogOut__VariantsArgs;
    args?: PlasmicLogOut__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLogOut__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLogOut__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogOut__ArgProps,
          internalVariantPropNames: PlasmicLogOut__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogOut__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "logOutPage") {
    func.displayName = "PlasmicLogOut";
  } else {
    func.displayName = `PlasmicLogOut.${nodeName}`;
  }
  return func;
}

export const PlasmicLogOut = Object.assign(
  // Top-level PlasmicLogOut renders the root element
  makeNodeComponent("logOutPage"),
  {
    // Helper components rendering sub-elements
    flex: makeNodeComponent("flex"),
    container: makeNodeComponent("container"),
    notice: makeNodeComponent("notice"),
    continueButton: makeNodeComponent("continueButton"),
    backButton: makeNodeComponent("backButton"),

    // Metadata about props expected for PlasmicLogOut
    internalVariantProps: PlasmicLogOut__VariantProps,
    internalArgProps: PlasmicLogOut__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/log-out",
      pagePath: "/log-out",
      params: {},
      query: {}
    })
  }
);

export default PlasmicLogOut;
/* prettier-ignore-end */
