/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: uSjUwNJyCcmf

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TextField from "../../TextField"; // plasmic-import: nhNi86WWHkJQ/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicSignUp.module.css"; // plasmic-import: uSjUwNJyCcmf/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 0qv-KGqIe6NJ/icon
import EnterIcon from "./icons/PlasmicIcon__Enter"; // plasmic-import: P5DSv3AH-d_Z/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Register",

    openGraph: {
      title: "Register",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    },
    twitter: {
      card: "summary_large_image" as const,
      title: "Register",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    }
  };
}

export type PlasmicSignUp__VariantMembers = {};
export type PlasmicSignUp__VariantsArgs = {};
type VariantPropType = keyof PlasmicSignUp__VariantsArgs;
export const PlasmicSignUp__VariantProps = new Array<VariantPropType>();

export type PlasmicSignUp__ArgsType = {};
type ArgPropType = keyof PlasmicSignUp__ArgsType;
export const PlasmicSignUp__ArgProps = new Array<ArgPropType>();

export type PlasmicSignUp__OverridesType = {
  signUpPage?: Flex__<"div">;
  flex?: Flex__<"div">;
  container?: Flex__<"div">;
  title?: Flex__<"h1">;
  firstNameContainer?: Flex__<typeof TextField>;
  firstNameError?: Flex__<"div">;
  firstNameErrorContent?: Flex__<"div">;
  lastNameContainer?: Flex__<typeof TextField>;
  lastNameError?: Flex__<"div">;
  lastNameErrorContent?: Flex__<"div">;
  emailContainer?: Flex__<typeof TextField>;
  emailError?: Flex__<"div">;
  emailErrorContent?: Flex__<"div">;
  passwordContainer?: Flex__<typeof TextField>;
  confirmPasswordContainer?: Flex__<typeof TextField>;
  passwordError?: Flex__<"div">;
  passwordErrorContent?: Flex__<"div">;
  signUpButton?: Flex__<"button">;
  generalError?: Flex__<"div">;
  generalErrorContent?: Flex__<"div">;
  logInRedirect?: Flex__<"div">;
  h1?: Flex__<"h1">;
  logInRedirectButton?: Flex__<"button">;
  alreadyLoggedIn?: Flex__<"div">;
  notice?: Flex__<"h1">;
  toDashboardButton?: Flex__<"button">;
  svg?: Flex__<"svg">;
};

export interface DefaultSignUpProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSignUp__RenderFunc(props: {
  variants: PlasmicSignUp__VariantsArgs;
  args: PlasmicSignUp__ArgsType;
  overrides: PlasmicSignUp__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "emailContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "passwordContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "firstNameContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "lastNameContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "confirmPasswordContainer.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"signUpPage"}
          data-plasmic-override={overrides.signUpPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.signUpPage
          )}
        >
          <div
            data-plasmic-name={"flex"}
            data-plasmic-override={overrides.flex}
            className={classNames("all", sty.flex)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames("all", sty.container)}
            >
              <h1
                data-plasmic-name={"title"}
                data-plasmic-override={overrides.title}
                className={classNames(
                  "all",
                  "h1",
                  "h1__6FNNC",
                  "__wab_text",
                  sty.title
                )}
              >
                {"Sign Up"}
              </h1>
              <TextField
                data-plasmic-name={"firstNameContainer"}
                data-plasmic-override={overrides.firstNameContainer}
                autoComplete={["given-name"]}
                autoFocus={true}
                className={classNames("__wab_instance", sty.firstNameContainer)}
                description={""}
                disabled={false}
                inputMode={"text"}
                label={
                  <div
                    className={classNames("all", "__wab_text", sty.text__pzeYw)}
                  >
                    {"First Name\n"}
                  </div>
                }
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "firstNameContainer",
                    "value"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                placeholder={"..."}
                showDescription={false}
                showLabel={true}
                type={"text"}
                value={generateStateValueProp($state, [
                  "firstNameContainer",
                  "value"
                ])}
              />

              <div
                data-plasmic-name={"firstNameError"}
                data-plasmic-override={overrides.firstNameError}
                className={classNames("all", sty.firstNameError)}
              >
                <div
                  data-plasmic-name={"firstNameErrorContent"}
                  data-plasmic-override={overrides.firstNameErrorContent}
                  className={classNames(
                    "all",
                    "__wab_text",
                    sty.firstNameErrorContent
                  )}
                >
                  {"..."}
                </div>
              </div>
              <TextField
                data-plasmic-name={"lastNameContainer"}
                data-plasmic-override={overrides.lastNameContainer}
                autoComplete={["family-name"]}
                autoFocus={true}
                className={classNames("__wab_instance", sty.lastNameContainer)}
                description={""}
                disabled={false}
                inputMode={"text"}
                label={
                  <div
                    className={classNames("all", "__wab_text", sty.text__gJusr)}
                  >
                    {"Last Name\n"}
                  </div>
                }
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "lastNameContainer",
                    "value"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                placeholder={"..."}
                showDescription={false}
                showLabel={true}
                type={"text"}
                value={generateStateValueProp($state, [
                  "lastNameContainer",
                  "value"
                ])}
              />

              <div
                data-plasmic-name={"lastNameError"}
                data-plasmic-override={overrides.lastNameError}
                className={classNames("all", sty.lastNameError)}
              >
                <div
                  data-plasmic-name={"lastNameErrorContent"}
                  data-plasmic-override={overrides.lastNameErrorContent}
                  className={classNames(
                    "all",
                    "__wab_text",
                    sty.lastNameErrorContent
                  )}
                >
                  {"..."}
                </div>
              </div>
              <TextField
                data-plasmic-name={"emailContainer"}
                data-plasmic-override={overrides.emailContainer}
                autoComplete={["email"]}
                autoFocus={true}
                className={classNames("__wab_instance", sty.emailContainer)}
                description={"ex. name@example.com"}
                disabled={false}
                inputMode={"email"}
                label={
                  <div
                    className={classNames("all", "__wab_text", sty.text__r7CGs)}
                  >
                    {"Email\n"}
                  </div>
                }
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "emailContainer",
                    "value"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                placeholder={"name@example.com"}
                showDescription={false}
                showLabel={true}
                type={"email"}
                value={generateStateValueProp($state, [
                  "emailContainer",
                  "value"
                ])}
              />

              <div
                data-plasmic-name={"emailError"}
                data-plasmic-override={overrides.emailError}
                className={classNames("all", sty.emailError)}
              >
                <div
                  data-plasmic-name={"emailErrorContent"}
                  data-plasmic-override={overrides.emailErrorContent}
                  className={classNames(
                    "all",
                    "__wab_text",
                    sty.emailErrorContent
                  )}
                >
                  {"..."}
                </div>
              </div>
              <TextField
                data-plasmic-name={"passwordContainer"}
                data-plasmic-override={overrides.passwordContainer}
                autoComplete={["off"]}
                className={classNames("__wab_instance", sty.passwordContainer)}
                description={""}
                disabled={false}
                inputMode={"none"}
                label={
                  <div
                    className={classNames("all", "__wab_text", sty.text__lxz3R)}
                  >
                    {"Password"}
                  </div>
                }
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "passwordContainer",
                    "value"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                placeholder={"..."}
                showDescription={false}
                showLabel={true}
                type={"password"}
                value={generateStateValueProp($state, [
                  "passwordContainer",
                  "value"
                ])}
              />

              <TextField
                data-plasmic-name={"confirmPasswordContainer"}
                data-plasmic-override={overrides.confirmPasswordContainer}
                autoComplete={["off"]}
                className={classNames(
                  "__wab_instance",
                  sty.confirmPasswordContainer
                )}
                description={""}
                disabled={false}
                inputMode={"none"}
                label={
                  <div
                    className={classNames("all", "__wab_text", sty.text__r7HcU)}
                  >
                    {"Confirm Password"}
                  </div>
                }
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "confirmPasswordContainer",
                    "value"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                placeholder={"..."}
                showDescription={false}
                showLabel={true}
                type={"password"}
                value={generateStateValueProp($state, [
                  "confirmPasswordContainer",
                  "value"
                ])}
              />

              <div
                data-plasmic-name={"passwordError"}
                data-plasmic-override={overrides.passwordError}
                className={classNames("all", sty.passwordError)}
              >
                <div
                  data-plasmic-name={"passwordErrorContent"}
                  data-plasmic-override={overrides.passwordErrorContent}
                  className={classNames(
                    "all",
                    "__wab_text",
                    sty.passwordErrorContent
                  )}
                >
                  {"..."}
                </div>
              </div>
              <button
                data-plasmic-name={"signUpButton"}
                data-plasmic-override={overrides.signUpButton}
                className={classNames(
                  "all",
                  "button",
                  "button__6FNNC",
                  sty.signUpButton
                )}
                ref={ref => {
                  $refs["signUpButton"] = ref;
                }}
              >
                <div
                  className={classNames("all", "__wab_text", sty.text__uIeda)}
                >
                  {"Create Account"}
                </div>
              </button>
              <div
                data-plasmic-name={"generalError"}
                data-plasmic-override={overrides.generalError}
                className={classNames("all", sty.generalError)}
              >
                <div
                  data-plasmic-name={"generalErrorContent"}
                  data-plasmic-override={overrides.generalErrorContent}
                  className={classNames(
                    "all",
                    "__wab_text",
                    sty.generalErrorContent
                  )}
                >
                  {"Password must be..."}
                </div>
              </div>
              <div
                data-plasmic-name={"logInRedirect"}
                data-plasmic-override={overrides.logInRedirect}
                className={classNames("all", sty.logInRedirect)}
              >
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    "all",
                    "h1",
                    "h1__6FNNC",
                    "__wab_text",
                    sty.h1
                  )}
                >
                  {"Already have an account?"}
                </h1>
                <button
                  data-plasmic-name={"logInRedirectButton"}
                  data-plasmic-override={overrides.logInRedirectButton}
                  className={classNames(
                    "all",
                    "button",
                    "button__6FNNC",
                    sty.logInRedirectButton
                  )}
                  onClick={async event => {
                    const $steps = {};

                    $steps["goToLogIn"] = true
                      ? (() => {
                          const actionArgs = { destination: `/log-in` };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToLogIn"] != null &&
                      typeof $steps["goToLogIn"] === "object" &&
                      typeof $steps["goToLogIn"].then === "function"
                    ) {
                      $steps["goToLogIn"] = await $steps["goToLogIn"];
                    }
                  }}
                  ref={ref => {
                    $refs["logInRedirectButton"] = ref;
                  }}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__wj1Pf)}
                  >
                    {"Log In"}
                  </div>
                </button>
              </div>
            </div>
            <div
              data-plasmic-name={"alreadyLoggedIn"}
              data-plasmic-override={overrides.alreadyLoggedIn}
              className={classNames("all", sty.alreadyLoggedIn)}
            >
              <h1
                data-plasmic-name={"notice"}
                data-plasmic-override={overrides.notice}
                className={classNames(
                  "all",
                  "h1",
                  "h1__6FNNC",
                  "__wab_text",
                  sty.notice
                )}
              >
                {"You are already logged in."}
              </h1>
              <button
                data-plasmic-name={"toDashboardButton"}
                data-plasmic-override={overrides.toDashboardButton}
                className={classNames(
                  "all",
                  "button",
                  "button__6FNNC",
                  sty.toDashboardButton
                )}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToDashboard"] = true
                    ? (() => {
                        const actionArgs = { destination: `/dashboard` };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToDashboard"] != null &&
                    typeof $steps["goToDashboard"] === "object" &&
                    typeof $steps["goToDashboard"].then === "function"
                  ) {
                    $steps["goToDashboard"] = await $steps["goToDashboard"];
                  }
                }}
                ref={ref => {
                  $refs["toDashboardButton"] = ref;
                }}
              >
                <EnterIcon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames("all", sty.svg)}
                  role={"img"}
                />

                <div
                  className={classNames("all", "__wab_text", sty.text__h6Mbn)}
                >
                  {"Go To Dashboard"}
                </div>
              </button>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  signUpPage: [
    "signUpPage",
    "flex",
    "container",
    "title",
    "firstNameContainer",
    "firstNameError",
    "firstNameErrorContent",
    "lastNameContainer",
    "lastNameError",
    "lastNameErrorContent",
    "emailContainer",
    "emailError",
    "emailErrorContent",
    "passwordContainer",
    "confirmPasswordContainer",
    "passwordError",
    "passwordErrorContent",
    "signUpButton",
    "generalError",
    "generalErrorContent",
    "logInRedirect",
    "h1",
    "logInRedirectButton",
    "alreadyLoggedIn",
    "notice",
    "toDashboardButton",
    "svg"
  ],
  flex: [
    "flex",
    "container",
    "title",
    "firstNameContainer",
    "firstNameError",
    "firstNameErrorContent",
    "lastNameContainer",
    "lastNameError",
    "lastNameErrorContent",
    "emailContainer",
    "emailError",
    "emailErrorContent",
    "passwordContainer",
    "confirmPasswordContainer",
    "passwordError",
    "passwordErrorContent",
    "signUpButton",
    "generalError",
    "generalErrorContent",
    "logInRedirect",
    "h1",
    "logInRedirectButton",
    "alreadyLoggedIn",
    "notice",
    "toDashboardButton",
    "svg"
  ],
  container: [
    "container",
    "title",
    "firstNameContainer",
    "firstNameError",
    "firstNameErrorContent",
    "lastNameContainer",
    "lastNameError",
    "lastNameErrorContent",
    "emailContainer",
    "emailError",
    "emailErrorContent",
    "passwordContainer",
    "confirmPasswordContainer",
    "passwordError",
    "passwordErrorContent",
    "signUpButton",
    "generalError",
    "generalErrorContent",
    "logInRedirect",
    "h1",
    "logInRedirectButton"
  ],
  title: ["title"],
  firstNameContainer: ["firstNameContainer"],
  firstNameError: ["firstNameError", "firstNameErrorContent"],
  firstNameErrorContent: ["firstNameErrorContent"],
  lastNameContainer: ["lastNameContainer"],
  lastNameError: ["lastNameError", "lastNameErrorContent"],
  lastNameErrorContent: ["lastNameErrorContent"],
  emailContainer: ["emailContainer"],
  emailError: ["emailError", "emailErrorContent"],
  emailErrorContent: ["emailErrorContent"],
  passwordContainer: ["passwordContainer"],
  confirmPasswordContainer: ["confirmPasswordContainer"],
  passwordError: ["passwordError", "passwordErrorContent"],
  passwordErrorContent: ["passwordErrorContent"],
  signUpButton: ["signUpButton"],
  generalError: ["generalError", "generalErrorContent"],
  generalErrorContent: ["generalErrorContent"],
  logInRedirect: ["logInRedirect", "h1", "logInRedirectButton"],
  h1: ["h1"],
  logInRedirectButton: ["logInRedirectButton"],
  alreadyLoggedIn: ["alreadyLoggedIn", "notice", "toDashboardButton", "svg"],
  notice: ["notice"],
  toDashboardButton: ["toDashboardButton", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  signUpPage: "div";
  flex: "div";
  container: "div";
  title: "h1";
  firstNameContainer: typeof TextField;
  firstNameError: "div";
  firstNameErrorContent: "div";
  lastNameContainer: typeof TextField;
  lastNameError: "div";
  lastNameErrorContent: "div";
  emailContainer: typeof TextField;
  emailError: "div";
  emailErrorContent: "div";
  passwordContainer: typeof TextField;
  confirmPasswordContainer: typeof TextField;
  passwordError: "div";
  passwordErrorContent: "div";
  signUpButton: "button";
  generalError: "div";
  generalErrorContent: "div";
  logInRedirect: "div";
  h1: "h1";
  logInRedirectButton: "button";
  alreadyLoggedIn: "div";
  notice: "h1";
  toDashboardButton: "button";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSignUp__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSignUp__VariantsArgs;
    args?: PlasmicSignUp__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSignUp__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSignUp__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSignUp__ArgProps,
          internalVariantPropNames: PlasmicSignUp__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSignUp__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "signUpPage") {
    func.displayName = "PlasmicSignUp";
  } else {
    func.displayName = `PlasmicSignUp.${nodeName}`;
  }
  return func;
}

export const PlasmicSignUp = Object.assign(
  // Top-level PlasmicSignUp renders the root element
  makeNodeComponent("signUpPage"),
  {
    // Helper components rendering sub-elements
    flex: makeNodeComponent("flex"),
    container: makeNodeComponent("container"),
    title: makeNodeComponent("title"),
    firstNameContainer: makeNodeComponent("firstNameContainer"),
    firstNameError: makeNodeComponent("firstNameError"),
    firstNameErrorContent: makeNodeComponent("firstNameErrorContent"),
    lastNameContainer: makeNodeComponent("lastNameContainer"),
    lastNameError: makeNodeComponent("lastNameError"),
    lastNameErrorContent: makeNodeComponent("lastNameErrorContent"),
    emailContainer: makeNodeComponent("emailContainer"),
    emailError: makeNodeComponent("emailError"),
    emailErrorContent: makeNodeComponent("emailErrorContent"),
    passwordContainer: makeNodeComponent("passwordContainer"),
    confirmPasswordContainer: makeNodeComponent("confirmPasswordContainer"),
    passwordError: makeNodeComponent("passwordError"),
    passwordErrorContent: makeNodeComponent("passwordErrorContent"),
    signUpButton: makeNodeComponent("signUpButton"),
    generalError: makeNodeComponent("generalError"),
    generalErrorContent: makeNodeComponent("generalErrorContent"),
    logInRedirect: makeNodeComponent("logInRedirect"),
    h1: makeNodeComponent("h1"),
    logInRedirectButton: makeNodeComponent("logInRedirectButton"),
    alreadyLoggedIn: makeNodeComponent("alreadyLoggedIn"),
    notice: makeNodeComponent("notice"),
    toDashboardButton: makeNodeComponent("toDashboardButton"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicSignUp
    internalVariantProps: PlasmicSignUp__VariantProps,
    internalArgProps: PlasmicSignUp__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/register",
      pagePath: "/register",
      params: {},
      query: {}
    })
  }
);

export default PlasmicSignUp;
/* prettier-ignore-end */
