/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxImportSource @plasmicapp/react-web-runtime */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FNNC7rfkE9HMPqXDPWwTm
// Component: C7cUxPqd2zr6

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { InteractiveMap } from "../../InteractiveMap"; // plasmic-import: XvO_ZZU8bF0U/codeComponent
import NavigationBar from "../../NavigationBar"; // plasmic-import: 9ar3kGz7iBUD/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 6FNNC7rfkE9HMPqXDPWwTm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicDashboard.module.css"; // plasmic-import: C7cUxPqd2zr6/css

import DoubleChevronRightIcon from "./icons/PlasmicIcon__DoubleChevronRight"; // plasmic-import: 4kOhv-a8yPCd/icon
import PeopleIcon from "./icons/PlasmicIcon__People"; // plasmic-import: 9nm8GnVbav_y/icon
import MovingTrashIcon from "./icons/PlasmicIcon__MovingTrash"; // plasmic-import: VWc3kj67KFnJ/icon
import MapAndPinIcon from "./icons/PlasmicIcon__MapAndPin"; // plasmic-import: 6t3FPM1-PqG4/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Dashboard",

    openGraph: {
      title: "Dashboard",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    },
    twitter: {
      card: "summary_large_image" as const,
      title: "Dashboard",

      images: [
        "https://site-assets.plasmic.app/7552d94556703d044c1d19d9a7de2ef2.png"
      ]
    }
  };
}

export type PlasmicDashboard__VariantMembers = {};
export type PlasmicDashboard__VariantsArgs = {};
type VariantPropType = keyof PlasmicDashboard__VariantsArgs;
export const PlasmicDashboard__VariantProps = new Array<VariantPropType>();

export type PlasmicDashboard__ArgsType = {};
type ArgPropType = keyof PlasmicDashboard__ArgsType;
export const PlasmicDashboard__ArgProps = new Array<ArgPropType>();

export type PlasmicDashboard__OverridesType = {
  dashboardPage?: Flex__<"div">;
  eventCards?: Flex__<"div">;
  activeEventCard?: Flex__<"div">;
  activeEventTitle?: Flex__<"div">;
  activeEventTitleIcon?: Flex__<"svg">;
  activeEventTitleContent?: Flex__<"h1">;
  activeEventCardValue?: Flex__<"div">;
  participantsCard?: Flex__<"div">;
  participantsCardValue?: Flex__<"div">;
  wasteCollectedCard?: Flex__<"div">;
  wasteCollectedCardValue?: Flex__<"div">;
  mapContainer?: Flex__<"div">;
  mapHeader?: Flex__<"div">;
  mapTitle?: Flex__<"h1">;
  interactiveMap?: Flex__<typeof InteractiveMap>;
  navigationBar?: Flex__<typeof NavigationBar>;
};

export interface DefaultDashboardProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDashboard__RenderFunc(props: {
  variants: PlasmicDashboard__VariantsArgs;
  args: PlasmicDashboard__ArgsType;
  overrides: PlasmicDashboard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"dashboardPage"}
          data-plasmic-override={overrides.dashboardPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_6FNNC7rfkE9HMPqXDPWwTm",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.dashboardPage
          )}
        >
          <div
            data-plasmic-name={"eventCards"}
            data-plasmic-override={overrides.eventCards}
            className={classNames("all", sty.eventCards)}
          >
            <div
              data-plasmic-name={"activeEventCard"}
              data-plasmic-override={overrides.activeEventCard}
              className={classNames("all", sty.activeEventCard)}
            >
              <div
                data-plasmic-name={"activeEventTitle"}
                data-plasmic-override={overrides.activeEventTitle}
                className={classNames("all", sty.activeEventTitle)}
              >
                <DoubleChevronRightIcon
                  data-plasmic-name={"activeEventTitleIcon"}
                  data-plasmic-override={overrides.activeEventTitleIcon}
                  className={classNames("all", sty.activeEventTitleIcon)}
                  role={"img"}
                />

                <h1
                  data-plasmic-name={"activeEventTitleContent"}
                  data-plasmic-override={overrides.activeEventTitleContent}
                  className={classNames(
                    "all",
                    "h1",
                    "h1__6FNNC",
                    "__wab_text",
                    sty.activeEventTitleContent
                  )}
                >
                  {"Active Event"}
                </h1>
              </div>
              <div
                data-plasmic-name={"activeEventCardValue"}
                data-plasmic-override={overrides.activeEventCardValue}
                className={classNames(
                  "all",
                  "__wab_text",
                  sty.activeEventCardValue
                )}
              >
                {"N/A"}
              </div>
            </div>
            <div
              data-plasmic-name={"participantsCard"}
              data-plasmic-override={overrides.participantsCard}
              className={classNames("all", sty.participantsCard)}
            >
              <div className={classNames("all", sty.freeBox___1PNiP)}>
                <PeopleIcon
                  className={classNames("all", sty.svg__cbREx)}
                  role={"img"}
                />

                <h1
                  className={classNames(
                    "all",
                    "h1",
                    "h1__6FNNC",
                    "__wab_text",
                    sty.h1__kYoid
                  )}
                >
                  {"Participants"}
                </h1>
              </div>
              <div
                data-plasmic-name={"participantsCardValue"}
                data-plasmic-override={overrides.participantsCardValue}
                className={classNames(
                  "all",
                  "__wab_text",
                  sty.participantsCardValue
                )}
              >
                {"N/A"}
              </div>
            </div>
            <div
              data-plasmic-name={"wasteCollectedCard"}
              data-plasmic-override={overrides.wasteCollectedCard}
              className={classNames("all", sty.wasteCollectedCard)}
            >
              <div className={classNames("all", sty.freeBox__buxYm)}>
                <MovingTrashIcon
                  className={classNames("all", sty.svg__xn0Vt)}
                  role={"img"}
                />

                <h1
                  className={classNames(
                    "all",
                    "h1",
                    "h1__6FNNC",
                    "__wab_text",
                    sty.h1__ikFl0
                  )}
                >
                  {"Waste Collected"}
                </h1>
              </div>
              <div
                data-plasmic-name={"wasteCollectedCardValue"}
                data-plasmic-override={overrides.wasteCollectedCardValue}
                className={classNames(
                  "all",
                  "__wab_text",
                  sty.wasteCollectedCardValue
                )}
              >
                {"N/A"}
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"mapContainer"}
            data-plasmic-override={overrides.mapContainer}
            className={classNames("all", sty.mapContainer)}
          >
            <div
              data-plasmic-name={"mapHeader"}
              data-plasmic-override={overrides.mapHeader}
              className={classNames("all", sty.mapHeader)}
            >
              <MapAndPinIcon
                className={classNames("all", sty.svg__yhAk1)}
                role={"img"}
              />

              <h1
                data-plasmic-name={"mapTitle"}
                data-plasmic-override={overrides.mapTitle}
                className={classNames(
                  "all",
                  "h1",
                  "h1__6FNNC",
                  "__wab_text",
                  sty.mapTitle
                )}
              >
                {"Live Event Heatmap"}
              </h1>
            </div>
            <InteractiveMap
              data-plasmic-name={"interactiveMap"}
              data-plasmic-override={overrides.interactiveMap}
              className={classNames("__wab_instance", sty.interactiveMap)}
            />
          </div>
          <NavigationBar
            data-plasmic-name={"navigationBar"}
            data-plasmic-override={overrides.navigationBar}
            className={classNames("__wab_instance", sty.navigationBar)}
            tab={"dashboard"}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  dashboardPage: [
    "dashboardPage",
    "eventCards",
    "activeEventCard",
    "activeEventTitle",
    "activeEventTitleIcon",
    "activeEventTitleContent",
    "activeEventCardValue",
    "participantsCard",
    "participantsCardValue",
    "wasteCollectedCard",
    "wasteCollectedCardValue",
    "mapContainer",
    "mapHeader",
    "mapTitle",
    "interactiveMap",
    "navigationBar"
  ],
  eventCards: [
    "eventCards",
    "activeEventCard",
    "activeEventTitle",
    "activeEventTitleIcon",
    "activeEventTitleContent",
    "activeEventCardValue",
    "participantsCard",
    "participantsCardValue",
    "wasteCollectedCard",
    "wasteCollectedCardValue"
  ],
  activeEventCard: [
    "activeEventCard",
    "activeEventTitle",
    "activeEventTitleIcon",
    "activeEventTitleContent",
    "activeEventCardValue"
  ],
  activeEventTitle: [
    "activeEventTitle",
    "activeEventTitleIcon",
    "activeEventTitleContent"
  ],
  activeEventTitleIcon: ["activeEventTitleIcon"],
  activeEventTitleContent: ["activeEventTitleContent"],
  activeEventCardValue: ["activeEventCardValue"],
  participantsCard: ["participantsCard", "participantsCardValue"],
  participantsCardValue: ["participantsCardValue"],
  wasteCollectedCard: ["wasteCollectedCard", "wasteCollectedCardValue"],
  wasteCollectedCardValue: ["wasteCollectedCardValue"],
  mapContainer: ["mapContainer", "mapHeader", "mapTitle", "interactiveMap"],
  mapHeader: ["mapHeader", "mapTitle"],
  mapTitle: ["mapTitle"],
  interactiveMap: ["interactiveMap"],
  navigationBar: ["navigationBar"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  dashboardPage: "div";
  eventCards: "div";
  activeEventCard: "div";
  activeEventTitle: "div";
  activeEventTitleIcon: "svg";
  activeEventTitleContent: "h1";
  activeEventCardValue: "div";
  participantsCard: "div";
  participantsCardValue: "div";
  wasteCollectedCard: "div";
  wasteCollectedCardValue: "div";
  mapContainer: "div";
  mapHeader: "div";
  mapTitle: "h1";
  interactiveMap: typeof InteractiveMap;
  navigationBar: typeof NavigationBar;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDashboard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDashboard__VariantsArgs;
    args?: PlasmicDashboard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicDashboard__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicDashboard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDashboard__ArgProps,
          internalVariantPropNames: PlasmicDashboard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDashboard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "dashboardPage") {
    func.displayName = "PlasmicDashboard";
  } else {
    func.displayName = `PlasmicDashboard.${nodeName}`;
  }
  return func;
}

export const PlasmicDashboard = Object.assign(
  // Top-level PlasmicDashboard renders the root element
  makeNodeComponent("dashboardPage"),
  {
    // Helper components rendering sub-elements
    eventCards: makeNodeComponent("eventCards"),
    activeEventCard: makeNodeComponent("activeEventCard"),
    activeEventTitle: makeNodeComponent("activeEventTitle"),
    activeEventTitleIcon: makeNodeComponent("activeEventTitleIcon"),
    activeEventTitleContent: makeNodeComponent("activeEventTitleContent"),
    activeEventCardValue: makeNodeComponent("activeEventCardValue"),
    participantsCard: makeNodeComponent("participantsCard"),
    participantsCardValue: makeNodeComponent("participantsCardValue"),
    wasteCollectedCard: makeNodeComponent("wasteCollectedCard"),
    wasteCollectedCardValue: makeNodeComponent("wasteCollectedCardValue"),
    mapContainer: makeNodeComponent("mapContainer"),
    mapHeader: makeNodeComponent("mapHeader"),
    mapTitle: makeNodeComponent("mapTitle"),
    interactiveMap: makeNodeComponent("interactiveMap"),
    navigationBar: makeNodeComponent("navigationBar"),

    // Metadata about props expected for PlasmicDashboard
    internalVariantProps: PlasmicDashboard__VariantProps,
    internalArgProps: PlasmicDashboard__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/dashboard",
      pagePath: "/dashboard",
      params: {},
      query: {}
    })
  }
);

export default PlasmicDashboard;
/* prettier-ignore-end */
