export const COCO80_LABELS: readonly string[] = [
  "person", "bicycle", "car", "motorcycle", "airplane", "bus", "train", "truck",
  "boat", "traffic light", "fire hydrant", "stop sign", "parking meter", "bench",
  "bird", "cat", "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra",
  "giraffe", "backpack", "umbrella", "handbag", "tie", "suitcase", "frisbee",
  "skis", "snowboard", "sports ball", "kite", "baseball bat", "baseball glove",
  "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
  "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange",
  "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair", "couch",
  "potted plant", "bed", "dining table", "toilet", "tv", "laptop", "mouse",
  "remote", "keyboard", "cell phone", "microwave", "oven", "toaster", "sink",
  "refrigerator", "book", "clock", "vase", "scissors", "teddy bear", "hair drier",
  "toothbrush",
];

export const COCO_CLASS_TO_WASTE: Readonly<Record<string, string>> = {
  bottle: "plastic",
  "wine glass": "glass",
  cup: "plastic",
  bowl: "plastic",
  vase: "glass",
  fork: "metal",
  knife: "metal",
  spoon: "metal",
  toothbrush: "plastic",
  book: "paper",
  banana: "food",
  apple: "food",
  sandwich: "food",
  orange: "food",
  broccoli: "food",
  carrot: "food",
  "hot dog": "food",
  pizza: "food",
  donut: "food",
  cake: "food",
};
